/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTBooleanLiteral extends SimpleNode {

  public boolean value;

  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97fffbde5885ed52ac4b92ca20e4b1c4 (do not edit this line) */
