/* Generated By:JJTree: Do not edit this line. ASTEmptyRDFSLabelSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTEmptyRDFSLabelSetting extends SimpleNode {

  public int emptyRDFSLabelSetting;

  public ASTEmptyRDFSLabelSetting(int id) {
    super(id);
  }

  public ASTEmptyRDFSLabelSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d48c3bce3df928b8d2edd850d2e8eb20 (do not edit this line) */
