/* Generated By:JJTree: Do not edit this line. ASTEmptyLocationSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTEmptyLocationSetting extends SimpleNode {
	
  public int emptyLocationSetting;
	
  public ASTEmptyLocationSetting(int id) {
    super(id);
  }

  public ASTEmptyLocationSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=939d32ed36571fa6e811de201bde25ef (do not edit this line) */
