/* Generated By:JJTree: Do not edit this line. ASTIfNotExistsDirective.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTIfNotExistsDirective extends SimpleNode {

  public int ifNotExistsSetting;

  public ASTIfNotExistsDirective(int id) {
    super(id);
  }

  public ASTIfNotExistsDirective(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f1da1e7746690775a074d904e5403b7 (do not edit this line) */
