/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEntityType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultEntityType extends SimpleNode {

  public int entityType;

  public ASTMMDefaultEntityType(int id) {
    super(id);
  }

  public ASTMMDefaultEntityType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4320917dc91f9fdbe2f3decb88c0bcfb (do not edit this line) */
