/* Generated By:JJTree: Do not edit this line. ASTMMDefaultShiftSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultShiftSetting extends SimpleNode {

  public int shiftSetting;

  public ASTMMDefaultShiftSetting(int id) {
    super(id);
  }

  public ASTMMDefaultShiftSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=74063f9143efd3a3d48f37722b3cc57f (do not edit this line) */
