/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyDataValueSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultEmptyDataValueSetting extends SimpleNode {

  public int emptyDataValueSetting;

  public ASTMMDefaultEmptyDataValueSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyDataValueSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1fb06bcd1a9af13ed2e060a087e30d2d (do not edit this line) */
