/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyRDFSLabelSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultEmptyRDFSLabelSetting extends SimpleNode {

  public int emptyRDFSLabelSetting;

  public ASTMMDefaultEmptyRDFSLabelSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyRDFSLabelSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc1c7b00935ffa7db64cab373cea51d8 (do not edit this line) */
