/* Generated By:JJTree: Do not edit this line. ASTMMDefaultLanguage.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultLanguage extends SimpleNode {

  public String language;

  public ASTMMDefaultLanguage(int id) {
    super(id);
  }

  public ASTMMDefaultLanguage(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c6930a95793974da34d38dc230d8635 (do not edit this line) */
