/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyLocationSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultEmptyLocationSetting extends SimpleNode {

  public int emptyLocationSetting;

  public ASTMMDefaultEmptyLocationSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyLocationSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84db567a33f73e2a68d4c0f90e49f278 (do not edit this line) */
