/* Generated By:JJTree: Do not edit this line. ASTMMDefaultValueEncoding.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultValueEncoding extends SimpleNode {

  public int encodingType;

  public ASTMMDefaultValueEncoding(int id) {
    super(id);
  }

  public ASTMMDefaultValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b18b461eb9fe9de760a1ca44b4f4678 (do not edit this line) */
