/* Generated By:JJTree: Do not edit this line. ASTMMDefaultDatatypePropertyValueType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultDatatypePropertyValueType extends SimpleNode {

  public int defaultType;

  public ASTMMDefaultDatatypePropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultDatatypePropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1619cdac985c8c59f5bc6edda35087c8 (do not edit this line) */
