/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfExistsSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultIfExistsSetting extends SimpleNode {

  public int ifExistsSetting;

  public ASTMMDefaultIfExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42579fd2785efcd653a734158cd9faf4 (do not edit this line) */
