/* Generated By:JJTree: Do not edit this line. ASTMMDefaultPropertyType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultPropertyType extends SimpleNode {

  public int defaultType;

  public ASTMMDefaultPropertyType(int id) {
    super(id);
  }

  public ASTMMDefaultPropertyType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40a8ba5dca10d87236afbfa9b19dd1a6 (do not edit this line) */
