/* Generated By:JJTree: Do not edit this line. ASTMMDefaultAnnotationPropertyValueType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultAnnotationPropertyValueType extends SimpleNode {

  public int defaultType;

  public ASTMMDefaultAnnotationPropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultAnnotationPropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68774dded0fb9a869bb99feb69196c03 (do not edit this line) */
