/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfNotExistsSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTMMDefaultIfNotExistsSetting extends SimpleNode {

  public int ifNotExistsSetting;

  public ASTMMDefaultIfNotExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfNotExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=33a441cfa41e370cfe5b6af6d4dfd946 (do not edit this line) */
