/* Generated By:JJTree: Do not edit this line. ASTOWLAllValuesFromDataType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTOWLAllValuesFromDataType extends SimpleNode {

  public int dataType;

  public ASTOWLAllValuesFromDataType(int id) {
    super(id);
  }

  public ASTOWLAllValuesFromDataType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0079873e5f7c7b32e7c0e804a43e1b3e (do not edit this line) */
