/* Generated By:JJTree: Do not edit this line. ASTOWLClassOrRestriction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTOWLClassOrRestriction extends SimpleNode {

  public boolean isNegated;

  public ASTOWLClassOrRestriction(int id) {
    super(id);
  }

  public ASTOWLClassOrRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=341a0840e3247f7cbe81f3f6aec7b005 (do not edit this line) */
