/* Generated By:JJTree: Do not edit this line. ASTOWLSomeValuesFromDataType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTOWLSomeValuesFromDataType extends SimpleNode {

  public int dataType;

  public ASTOWLSomeValuesFromDataType(int id) {
    super(id);
  }

  public ASTOWLSomeValuesFromDataType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5a925c2e7edbd818909dd4c25039415 (do not edit this line) */
