/* Generated By:JJTree: Do not edit this line. ASTPrefix.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTPrefix extends SimpleNode {

  public String prefix;

  public ASTPrefix(int id) {
    super(id);
  }

  public ASTPrefix(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f7a3543381fc49d3ebe5920a35a4cfe (do not edit this line) */
