/* Generated By:JJTree: Do not edit this line. ASTSourceSpecification.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTSourceSpecification extends SimpleNode {

  public String source, location, literal;

  public ASTSourceSpecification(int id) {
    super(id);
  }

  public ASTSourceSpecification(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1478ca7a2e9cfafd9f828bd2fe95f7d5 (do not edit this line) */
