/* Generated By:JJTree: Do not edit this line. ASTValueExtraction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;

public
class ASTValueExtraction extends SimpleNode {

  public String extractionType;

  public ASTValueExtraction(int id) {
    super(id);
  }

  public ASTValueExtraction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9014460f6c6f5236efa9eaf613054b4 (do not edit this line) */
