/* Generated By:JJTree: Do not edit this line. ASTValueEncoding.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.protege.owl.mm.parser;


public
class ASTValueEncoding extends SimpleNode {

  public int encodingType;
  public String defaultLocationValue;
  public int defaultShiftSetting, defaultEmptyLocationSetting;

  public ASTValueEncoding(int id) {
    super(id);
  }

  public ASTValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85c6ea0101d5ddedf2f0d3b165733956 (do not edit this line) */
