/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 5.0 */
package org.protege.owl.mm.parser;

public interface MappingMasterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTMMEXPRESSION = 1;
  public int JJTOWLEXPRESSION = 2;
  public int JJTMMDEFAULTVALUEENCODING = 3;
  public int JJTMMDEFAULTSHIFTSETTING = 4;
  public int JJTMMDEFAULTEMPTYLOCATIONSETTING = 5;
  public int JJTMMDEFAULTEMPTYDATAVALUESETTING = 6;
  public int JJTMMDEFAULTIFEXISTSSETTING = 7;
  public int JJTMMDEFAULTIFNOTEXISTSSETTING = 8;
  public int JJTMMDEFAULTEMPTYRDFIDSETTING = 9;
  public int JJTMMDEFAULTEMPTYRDFSLABELSETTING = 10;
  public int JJTMMDEFAULTENTITYTYPE = 11;
  public int JJTMMDEFAULTLANGUAGE = 12;
  public int JJTMMDEFAULTPREFIX = 13;
  public int JJTMMDEFAULTNAMESPACE = 14;
  public int JJTMMDEFAULTPROPERTYVALUETYPE = 15;
  public int JJTMMDEFAULTDATATYPEPROPERTYVALUETYPE = 16;
  public int JJTMMDEFAULTANNOTATIONPROPERTYVALUETYPE = 17;
  public int JJTMMDEFAULTPROPERTYTYPE = 18;
  public int JJTOWLCLASSDECLARATION = 19;
  public int JJTOWLEQUIVALENTTO = 20;
  public int JJTOWLSUBCLASSOF = 21;
  public int JJTOWLINDIVIDUALDECLARATION = 22;
  public int JJTSAMEAS = 23;
  public int JJTDIFFERENTFROM = 24;
  public int JJTVOID = 25;
  public int JJTFACT = 26;
  public int JJTANNOTATIONFACT = 27;
  public int JJTOWLPROPERTY = 28;
  public int JJTOWLINDIVIDUAL = 29;
  public int JJTNAME = 30;
  public int JJTOWLPROPERTYVALUE = 31;
  public int JJTLITERAL = 32;
  public int JJTINTEGERLITERAL = 33;
  public int JJTFLOATLITERAL = 34;
  public int JJTSTRINGLITERAL = 35;
  public int JJTBOOLEANLITERAL = 36;
  public int JJTOWLCLASSEXPRESSION = 37;
  public int JJTOWLUNIONCLASS = 38;
  public int JJTOWLINTERSECTIONCLASS = 39;
  public int JJTOWLCLASSORRESTRICTION = 40;
  public int JJTOWLENUMERATEDCLASS = 41;
  public int JJTOWLNAMEDCLASS = 42;
  public int JJTSOURCESPECIFICATION = 43;
  public int JJTOWLRESTRICTION = 44;
  public int JJTOWLMAXCARDINALITY = 45;
  public int JJTOWLMINCARDINALITY = 46;
  public int JJTOWLALLVALUESFROM = 47;
  public int JJTOWLHASVALUE = 48;
  public int JJTOWLCARDINALITY = 49;
  public int JJTOWLALLVALUESFROMCLASS = 50;
  public int JJTOWLALLVALUESFROMDATATYPE = 51;
  public int JJTOWLSOMEVALUESFROM = 52;
  public int JJTOWLSOMEVALUESFROMCLASS = 53;
  public int JJTOWLSOMEVALUESFROMDATATYPE = 54;
  public int JJTREFERENCE = 55;
  public int JJTENTITYTYPE = 56;
  public int JJTVALUEENCODING = 57;
  public int JJTEMPTYLOCATIONSETTING = 58;
  public int JJTIFEXISTSDIRECTIVE = 59;
  public int JJTIFNOTEXISTSDIRECTIVE = 60;
  public int JJTEMPTYDATAVALUESETTING = 61;
  public int JJTEMPTYRDFSLABELSETTING = 62;
  public int JJTEMPTYRDFIDSETTING = 63;
  public int JJTSHIFTSETTING = 64;
  public int JJTDEFAULTDATAVALUE = 65;
  public int JJTDEFAULTLOCATIONVALUE = 66;
  public int JJTDEFAULTID = 67;
  public int JJTDEFAULTLABEL = 68;
  public int JJTPREFIX = 69;
  public int JJTLANGUAGE = 70;
  public int JJTNAMESPACE = 71;
  public int JJTVALUESPECIFICATION = 72;
  public int JJTVALUESPECIFICATIONITEM = 73;
  public int JJTVALUEEXTRACTIONFUNCTION = 74;
  public int JJTSTRINGORREFERENCE = 75;
  public int JJTTYPES = 76;


  public String[] jjtNodeName = {
    "Expression",
    "MMExpression",
    "OWLExpression",
    "MMDefaultValueEncoding",
    "MMDefaultShiftSetting",
    "MMDefaultEmptyLocationSetting",
    "MMDefaultEmptyDataValueSetting",
    "MMDefaultIfExistsSetting",
    "MMDefaultIfNotExistsSetting",
    "MMDefaultEmptyRDFIDSetting",
    "MMDefaultEmptyRDFSLabelSetting",
    "MMDefaultEntityType",
    "MMDefaultLanguage",
    "MMDefaultPrefix",
    "MMDefaultNamespace",
    "MMDefaultPropertyValueType",
    "MMDefaultDatatypePropertyValueType",
    "MMDefaultAnnotationPropertyValueType",
    "MMDefaultPropertyType",
    "OWLClassDeclaration",
    "OWLEquivalentTo",
    "OWLSubclassOf",
    "OWLIndividualDeclaration",
    "SameAs",
    "DifferentFrom",
    "void",
    "Fact",
    "AnnotationFact",
    "OWLProperty",
    "OWLIndividual",
    "Name",
    "OWLPropertyValue",
    "Literal",
    "IntegerLiteralNode",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "OWLClassExpression",
    "OWLUnionClass",
    "OWLIntersectionClass",
    "OWLClassOrRestriction",
    "OWLEnumeratedClass",
    "OWLNamedClass",
    "SourceSpecification",
    "OWLRestriction",
    "OWLMaxCardinality",
    "OWLMinCardinality",
    "OWLAllValuesFrom",
    "OWLHasValue",
    "OWLCardinality",
    "OWLAllValuesFromClass",
    "OWLAllValuesFromDataType",
    "OWLSomeValuesFrom",
    "OWLSomeValuesFromClass",
    "OWLSomeValuesFromDataType",
    "Reference",
    "OWLEntityType",
    "ValueEncoding",
    "EmptyLocationSetting",
    "IfExistsDirective",
    "IfNotExistsDirective",
    "EmptyDataValueSetting",
    "EmptyRDFSLabelSetting",
    "EmptyRDFIDSetting",
    "ShiftSetting",
    "DefaultDataValue",
    "DefaultLocationValue",
    "DefaultID",
    "DefaultLabel",
    "Prefix",
    "Language",
    "Namespace",
    "ValueSpecification",
    "ValueSpecificationItem",
    "ValueExtractionFunction",
    "StringOrReference",
    "Types",
  };
}
/* JavaCC - OriginalChecksum=8db6e8fd6c030bd2393a45b064a45ec1 (do not edit this line) */
