/* Generated By:JJTree&JavaCC: Do not edit this line. MappingMasterParserConstants.java */
package org.protege.owl.mm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MappingMasterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int INDIVIDUAL = 14;
  /** RegularExpression Id. */
  int EQUIVALENT_TO = 15;
  /** RegularExpression Id. */
  int SUBCLASS_OF = 16;
  /** RegularExpression Id. */
  int FACTS = 17;
  /** RegularExpression Id. */
  int TYPES = 18;
  /** RegularExpression Id. */
  int ANNOTATIONS = 19;
  /** RegularExpression Id. */
  int SAME_AS = 20;
  /** RegularExpression Id. */
  int DIFFERENT_FROM = 21;
  /** RegularExpression Id. */
  int SOME = 22;
  /** RegularExpression Id. */
  int ONLY = 23;
  /** RegularExpression Id. */
  int VALUE = 24;
  /** RegularExpression Id. */
  int MIN = 25;
  /** RegularExpression Id. */
  int MAX = 26;
  /** RegularExpression Id. */
  int EXACTLY = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int XSD_DATETIME = 33;
  /** RegularExpression Id. */
  int XSD_LONG = 34;
  /** RegularExpression Id. */
  int XSD_STRING = 35;
  /** RegularExpression Id. */
  int XSD_INT = 36;
  /** RegularExpression Id. */
  int XSD_SHORT = 37;
  /** RegularExpression Id. */
  int XSD_BOOLEAN = 38;
  /** RegularExpression Id. */
  int XSD_DOUBLE = 39;
  /** RegularExpression Id. */
  int XSD_FLOAT = 40;
  /** RegularExpression Id. */
  int XSD_TIME = 41;
  /** RegularExpression Id. */
  int XSD_DURATION = 42;
  /** RegularExpression Id. */
  int RDF_XMLLITERAL = 43;
  /** RegularExpression Id. */
  int MM_LOCATION_WITH_DUPLICATES = 44;
  /** RegularExpression Id. */
  int MM_LOCATION = 45;
  /** RegularExpression Id. */
  int RDF_ID = 46;
  /** RegularExpression Id. */
  int RDFS_LABEL = 47;
  /** RegularExpression Id. */
  int XML_LANG = 48;
  /** RegularExpression Id. */
  int MM_NULL = 49;
  /** RegularExpression Id. */
  int MM_DATA_VALUE = 50;
  /** RegularExpression Id. */
  int MM_DEFAULT_VALUE_ENCODING = 51;
  /** RegularExpression Id. */
  int MM_DEFAULT_ENTITY_TYPE = 52;
  /** RegularExpression Id. */
  int MM_DEFAULT_PROPERTY_TYPE = 53;
  /** RegularExpression Id. */
  int MM_DEFAULT_PROPERTY_VALUE_TYPE = 54;
  /** RegularExpression Id. */
  int MM_DEFAULT_DATA_PROPERTY_VALUE_TYPE = 55;
  /** RegularExpression Id. */
  int MM_DEFAULT_ANNOTATION_PROPERTY_VALUE_TYPE = 56;
  /** RegularExpression Id. */
  int MM_DEFAULT_SHIFT = 57;
  /** RegularExpression Id. */
  int MM_DEFAULT_EMPTY_DATA_VALUE = 58;
  /** RegularExpression Id. */
  int MM_DEFAULT_EMPTY_LOCATION = 59;
  /** RegularExpression Id. */
  int MM_DEFAULT_EMPTY_RDF_ID = 60;
  /** RegularExpression Id. */
  int MM_DEFAULT_EMPTY_RDFS_LABEL = 61;
  /** RegularExpression Id. */
  int MM_DEFAULT_IF_EXISTS = 62;
  /** RegularExpression Id. */
  int MM_DEFAULT_IF_NOT_EXISTS = 63;
  /** RegularExpression Id. */
  int MM_UNTYPED = 64;
  /** RegularExpression Id. */
  int MM_PREFIX = 65;
  /** RegularExpression Id. */
  int MM_NAMESPACE = 66;
  /** RegularExpression Id. */
  int CELL_WILDCARD = 67;
  /** RegularExpression Id. */
  int RDFS_CLASS = 68;
  /** RegularExpression Id. */
  int RDF_PROPERTY = 69;
  /** RegularExpression Id. */
  int OWL_CLASS = 70;
  /** RegularExpression Id. */
  int OWL_THING = 71;
  /** RegularExpression Id. */
  int OWL_OBJECT_PROPERTY = 72;
  /** RegularExpression Id. */
  int OWL_DATA_PROPERTY = 73;
  /** RegularExpression Id. */
  int MM_TO_UPPER_CASE = 74;
  /** RegularExpression Id. */
  int MM_TO_LOWER_CASE = 75;
  /** RegularExpression Id. */
  int MM_TRIM = 76;
  /** RegularExpression Id. */
  int MM_CAPTURING = 77;
  /** RegularExpression Id. */
  int MM_REVERSE = 78;
  /** RegularExpression Id. */
  int MM_REPLACE = 79;
  /** RegularExpression Id. */
  int MM_REPLACE_ALL = 80;
  /** RegularExpression Id. */
  int MM_REPLACE_FIRST = 81;
  /** RegularExpression Id. */
  int MM_APPEND = 82;
  /** RegularExpression Id. */
  int MM_PREPEND = 83;
  /** RegularExpression Id. */
  int MM_DEFAULT_LOCATION_VALUE = 84;
  /** RegularExpression Id. */
  int MM_DEFAULT_DATA_VALUE = 85;
  /** RegularExpression Id. */
  int MM_DEFAULT_ID = 86;
  /** RegularExpression Id. */
  int MM_DEFAULT_LABEL = 87;
  /** RegularExpression Id. */
  int MM_DEFAULT_PREFIX = 88;
  /** RegularExpression Id. */
  int MM_DEFAULT_NAMESPACE = 89;
  /** RegularExpression Id. */
  int MM_DEFAULT_LANGUAGE = 90;
  /** RegularExpression Id. */
  int MM_NO_SHIFT = 91;
  /** RegularExpression Id. */
  int MM_SHIFT_UP = 92;
  /** RegularExpression Id. */
  int MM_SHIFT_DOWN = 93;
  /** RegularExpression Id. */
  int MM_SHIFT_LEFT = 94;
  /** RegularExpression Id. */
  int MM_SHIFT_RIGHT = 95;
  /** RegularExpression Id. */
  int MM_ERROR_IF_EMPTY_LOCATION = 96;
  /** RegularExpression Id. */
  int MM_WARNING_IF_EMPTY_LOCATION = 97;
  /** RegularExpression Id. */
  int MM_SKIP_IF_EMPTY_LOCATION = 98;
  /** RegularExpression Id. */
  int MM_PROCESS_IF_EMPTY_LOCATION = 99;
  /** RegularExpression Id. */
  int MM_PROCESS_IF_EMPTY_DATA_VALUE = 100;
  /** RegularExpression Id. */
  int MM_ERROR_IF_EMPTY_DATA_VALUE = 101;
  /** RegularExpression Id. */
  int MM_WARNING_IF_EMPTY_DATA_VALUE = 102;
  /** RegularExpression Id. */
  int MM_SKIP_IF_EMPTY_DATA_VALUE = 103;
  /** RegularExpression Id. */
  int MM_PROCESS_IF_EMPTY_ID = 104;
  /** RegularExpression Id. */
  int MM_ERROR_IF_EMPTY_ID = 105;
  /** RegularExpression Id. */
  int MM_WARNING_IF_EMPTY_ID = 106;
  /** RegularExpression Id. */
  int MM_SKIP_IF_EMPTY_ID = 107;
  /** RegularExpression Id. */
  int MM_PROCESS_IF_EMPTY_LABEL = 108;
  /** RegularExpression Id. */
  int MM_ERROR_IF_EMPTY_LABEL = 109;
  /** RegularExpression Id. */
  int MM_WARNING_IF_EMPTY_LABEL = 110;
  /** RegularExpression Id. */
  int MM_SKIP_IF_EMPTY_LABEL = 111;
  /** RegularExpression Id. */
  int MM_RESOLVE_IF_EXISTS = 112;
  /** RegularExpression Id. */
  int MM_SKIP_IF_EXISTS = 113;
  /** RegularExpression Id. */
  int MM_WARNING_IF_EXISTS = 114;
  /** RegularExpression Id. */
  int MM_ERROR_IF_EXISTS = 115;
  /** RegularExpression Id. */
  int MM_CREATE_IF_NOT_EXISTS = 116;
  /** RegularExpression Id. */
  int MM_SKIP_IF_NOT_EXISTS = 117;
  /** RegularExpression Id. */
  int MM_WARNING_IF_NOT_EXISTS = 118;
  /** RegularExpression Id. */
  int MM_ERROR_IF_NOT_EXISTS = 119;
  /** RegularExpression Id. */
  int STRING_LITERAL = 120;
  /** RegularExpression Id. */
  int QUOTED_NAME_LITERAL = 121;
  /** RegularExpression Id. */
  int IDENTIFIER = 122;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 123;
  /** RegularExpression Id. */
  int LONG_LITERAL = 124;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 125;
  /** RegularExpression Id. */
  int LETTER = 126;
  /** RegularExpression Id. */
  int DIGIT = 127;
  /** RegularExpression Id. */
  int EXPONENT = 128;
  /** RegularExpression Id. */
  int LOCATION_SPECIFICATION = 129;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<CLASS>",
    "<INDIVIDUAL>",
    "<EQUIVALENT_TO>",
    "<SUBCLASS_OF>",
    "<FACTS>",
    "<TYPES>",
    "<ANNOTATIONS>",
    "<SAME_AS>",
    "<DIFFERENT_FROM>",
    "<SOME>",
    "<ONLY>",
    "<VALUE>",
    "<MIN>",
    "<MAX>",
    "<EXACTLY>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<TRUE>",
    "<FALSE>",
    "\"xsd:dateTime\"",
    "\"xsd:long\"",
    "\"xsd:string\"",
    "\"xsd:int\"",
    "\"xsd:short\"",
    "\"xsd:boolean\"",
    "\"xsd:double\"",
    "\"xsd:float\"",
    "\"xsd:time\"",
    "\"xsd:duration\"",
    "\"rdf:XMLLiteral\"",
    "\"mm:LocationWithDuplicates\"",
    "\"mm:Location\"",
    "\"rdf:ID\"",
    "\"rdfs:label\"",
    "\"xml:lang\"",
    "\"mm:null\"",
    "\"mm:DataValue\"",
    "\"mm:DefaultValueEncoding\"",
    "\"mm:DefaultEntityType\"",
    "\"mm:DefaultPropertyType\"",
    "\"mm:DefaultPropertyValueType\"",
    "\"mm:DefaultDataPropertyValueType\"",
    "\"mm:DefaultAnnotationPropertyValueType\"",
    "\"mm:DefaultShift\"",
    "\"mm:DefaultEmptyDataValue\"",
    "\"mm:DefaultEmptyLocation\"",
    "\"mm:DefaultEmptyID\"",
    "\"mm:DefaultEmptyLabel\"",
    "\"mm:DefaultIfExists\"",
    "\"mm:DefaultIfNotExists\"",
    "\"mm:Untyped\"",
    "\"mm:Prefix\"",
    "\"mm:Namespace\"",
    "\"*\"",
    "\"rdfs:class\"",
    "\"rdf:property\"",
    "\"Class\"",
    "\"Individual\"",
    "\"ObjectProperty\"",
    "\"DataProperty\"",
    "\"mm:toUpperCase\"",
    "\"mm:toLowerCase\"",
    "\"mm:trim\"",
    "\"mm:capturing\"",
    "\"mm:reverse\"",
    "\"mm:replace\"",
    "\"mm:replaceAll\"",
    "\"mm:replaceFirst\"",
    "\"mm:append\"",
    "\"mm:prepend\"",
    "\"mm:DefaultLocationValue\"",
    "\"mm:DefaultDataValue\"",
    "\"mm:DefaultID\"",
    "\"mm:DefaultLabel\"",
    "\"mm:DefaultPrefix\"",
    "\"mm:DefaultNamespace\"",
    "\"mm:DefaultLanguage\"",
    "\"mm:NoShift\"",
    "\"mm:ShiftUp\"",
    "\"mm:ShiftDown\"",
    "\"mm:ShiftLeft\"",
    "\"mm:ShiftRight\"",
    "\"mm:ErrorIfEmptyLocation\"",
    "\"mm:WarningIfEmptyLocation\"",
    "\"mm:SkipIfEmptyLocation\"",
    "\"mm:ProcessIfEmptyLocation\"",
    "\"mm:ProcessIfEmptyDataValue\"",
    "\"mm:ErrorIfEmptyDataValue\"",
    "\"mm:WarningIfEmptyDataValue\"",
    "\"mm:SkipIfEmptyDataValue\"",
    "\"mm:ProcessIfEmptyID\"",
    "\"mm:ErrorIfEmptyID\"",
    "\"mm:WarningIfEmptyID\"",
    "\"mm:SkipIfEmptyID\"",
    "\"mm:ProcessIfEmptyLabel\"",
    "\"mm:ErrorIfEmptyLabel\"",
    "\"mm:WarningIfEmptyLable\"",
    "\"mm:SkipIfEmptyLabel\"",
    "\"mm:ResolveIfExists\"",
    "\"mm:SkipIfExists\"",
    "\"mm:WarningIfExists\"",
    "\"mm:ErrorIfExists\"",
    "\"mm:CreateIfNotExists\"",
    "\"mm:SkipIfNotExists\"",
    "\"mm:WarningIfNotExists\"",
    "\"mm:ErrorIfNotExists\"",
    "<STRING_LITERAL>",
    "<QUOTED_NAME_LITERAL>",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "<LONG_LITERAL>",
    "<FLOAT_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<EXPONENT>",
    "<LOCATION_SPECIFICATION>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "\"@\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
  };

}
