/**
 * In addition to the parser itself, this package contains JJTree-generated node files (named AST*.java) that were
 * manually modified to add extra state. (JJTree has no way of specifying the addition of this state to generated 
 * AST node classes.) 
 *
 * By default AST files generated by JJTree are placed in the ./target/generate-sources directory.
 * If an AST file for a node is present in this directory then the JJTree Maven plugin simply copies
 * the file to the ./target/generate-sources directory. Unlike the generated files, the AST files in this directory 
 * are effectively under souerce control.
 *
 * (One option would be to tell the JavaCC Maven plugin to place the generated node files directly into the source tree 
 * but the JavaCC Maven plugin seems to overwrite modified AST files using this approach. This we need to copy
 * any modified AST files into this source package directory and keep unmodified AST files in the default
 * ./target/generated-sources directory.)
 */

package org.protege.owl.mm.parser;
