/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationProperty.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTAnnotationProperty extends SimpleNode {
  public ASTAnnotationProperty(int id) {
    super(id);
  }

  public ASTAnnotationProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=90572760ad8f5486fc48afc2643202dd (do not edit this line) */
