/* Generated By:JJTree: Do not edit this line. ASTAnnotationValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTAnnotationValue extends SimpleNode {
  public ASTAnnotationValue(int id) {
    super(id);
  }

  public ASTAnnotationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=2b7a294e5f667a9167446229ce6276f4 (do not edit this line) */
