/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationAssertions.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTAnnotationAssertion extends SimpleNode {
  public ASTAnnotationAssertion(int id) {
    super(id);
  }

  public ASTAnnotationAssertion(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=ead49f7e26fdad812b342627be36080c (do not edit this line) */
