/* Generated By:JJTree: Do not edit this line. ASTBuiltInFunction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import javax.annotation.Nonnull;
import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTBuiltInFunction extends SimpleNode {

  public int functionType; /* Manually added */

  public ASTBuiltInFunction(int id) {
    super(id);
  }

  public ASTBuiltInFunction(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Nonnull
  public int getFunctionType() { /* XXX: Manually added */
     return functionType;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=4036dc3147fde08f6bc1793ab0a8b9ab (do not edit this line) */
