/* Generated By:JJTree: Do not edit this line. ASTBuiltInFunctionPipe.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTBuiltInFunctionPipe extends SimpleNode {
  public ASTBuiltInFunctionPipe(int id) {
    super(id);
  }

  public ASTBuiltInFunctionPipe(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=820d8a83f8723a966b2995e883a11b7b (do not edit this line) */
