/* Generated By:JJTree: Do not edit this line. ASTCardinalityValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTCardinalityValue extends SimpleNode {
  public ASTCardinalityValue(int id) {
    super(id);
  }

  public ASTCardinalityValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1298354c67976391244d198a2110e9cf (do not edit this line) */
