/* Generated By:JJTree: Do not edit this line. ASTClassExpressionFiller.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTClassExpressionFiller extends SimpleNode {
  public ASTClassExpressionFiller(int id) {
    super(id);
  }

  public ASTClassExpressionFiller(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=25d3a3f4040a6046fbc321bdddb560ed (do not edit this line) */
