/* Generated By:JJTree: Do not edit this line. ASTOWLDataMaxCardinality.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTDataMaxCardinality extends SimpleNode {

  public int cardinality; /* XXX: Manually added */
  public int datatype; /* XXX: Manually added */

  public ASTDataMaxCardinality(int id) {
    super(id);
  }

  public ASTDataMaxCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getCardinality() { /* XXX: Manually added */
     return cardinality;
  }

  public int getDatatype() { /* XXX: Manually added */
     return datatype;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=6a0cb8618cf68c3488f59b0f0d5fa606 (do not edit this line) */
