/* Generated By:JJTree: Do not edit this line. ASTDataFact.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTDataFact extends SimpleNode {
  public ASTDataFact(int id) {
    super(id);
  }

  public ASTDataFact(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=68c2db80c2a40ebf4bf6e3ec757fc265 (do not edit this line) */
