/* Generated By:JJTree: Do not edit this line. ASTOWLDataExactCardinality.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTDataExactCardinality extends SimpleNode {

  public int cardinality; /* XXX: Manually added */
  public int datatype; /* XXX: Manually added */

  public ASTDataExactCardinality(int id) {
    super(id);
  }

  public ASTDataExactCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getCardinality() { /* XXX: Manually added */
     return cardinality;
  }

  public int getDatatype() { /* XXX: Manually added */
     return datatype;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=dca8c4c7e7e5f66ca8ba66d4a4337e8e (do not edit this line) */
