/* Generated By:JJTree: Do not edit this line. ASTOWLDataMinCardinality.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTDataMinCardinality extends SimpleNode {

  public int cardinality; /* XXX: Manually added */
  public int datatype; /* XXX: Manually added */

  public ASTDataMinCardinality(int id) {
    super(id);
  }

  public ASTDataMinCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getCardinality() { /* XXX: Manually added */
     return cardinality;
  }

  public int getDatatype() { /* XXX: Manually added */
     return datatype;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=67aad5b38c11b073e3f19497ca07abad (do not edit this line) */
