/* Generated By:JJTree: Do not edit this line. ASTOWLEquivalentClasses.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTEquivalentClasses extends SimpleNode {
  public ASTEquivalentClasses(int id) {
    super(id);
  }

  public ASTEquivalentClasses(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=2dd4f239167a75e4a1c12784bc85bcbc (do not edit this line) */
