/* Generated By:JJTree: Do not edit this line. ASTExactCardinalityValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTFiller extends SimpleNode {

  public int datatype = -1; /* XXX: Manually added */

  public ASTFiller(int id) {
    super(id);
  }

  public ASTFiller(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getDatatype() { /* XXX: Manually added */
     return datatype;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=9e3b683a75b211205d6fc6f0412b8813 (do not edit this line) */
