/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTFloatLiteral extends SimpleNode {

  public float lexicalValue; /* XXX: Manually added */

  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

  public float getLexicalValue() { /* XXX: Manually added */
     return lexicalValue;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=63c8181140e40265d5b2e0ec924a3f38 (do not edit this line) */
