/* Generated By:JJTree: Do not edit this line. ASTOWLIndividualDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTIndividualDeclaration extends SimpleNode {
  public ASTIndividualDeclaration(int id) {
    super(id);
  }

  public ASTIndividualDeclaration(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=153d4f571d649882b7b81794f9e0d596 (do not edit this line) */
