/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTIntegerLiteral extends SimpleNode {

  public int lexicalValue; /* XXX: Manually added */

  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getLexicalValue() { /* XXX: Manually added */
    return lexicalValue;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=c848805490669a0fc2e4fad332a947e7 (do not edit this line) */
