/* Generated By:JJTree: Do not edit this line. ASTName.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTName extends SimpleNode {

  public String name; /* XXX: Manually added */

  public int entityType; /* XXX: Manually added */

  public ASTName(int id) {
    super(id);
  }

  public ASTName(MappingMasterParser p, int id) {
    super(p, id);
  }

  public String getValue() { /* XXX: Manually added */
    return name;
  }

  public int getEntityType() { /* XXX: Manually added */
    return entityType;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=f6567476445147de69b8300dd9b3fcdc (do not edit this line) */
