/* Generated By:JJTree: Do not edit this line. ASTOWLObjectExactCardinality.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTObjectExactCardinality extends SimpleNode {

  public boolean hasExplicitClassExpression; /* XXX: Manually added */

  public ASTObjectExactCardinality(int id) {
    super(id);
  }

  public ASTObjectExactCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  public boolean hasExplicitClassExpression() { /* XXX: Manually added */
     return hasExplicitClassExpression;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=ee566aad0ac9ca2ccd00a9b12fc69fd8 (do not edit this line) */
