/* Generated By:JJTree: Do not edit this line. ASTOWLObjectMinCardinality.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTObjectMinCardinality extends SimpleNode {

  public boolean hasExplicitClassExpression; /* XXX: Manually added */

  public ASTObjectMinCardinality(int id) {
    super(id);
  }

  public ASTObjectMinCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  public boolean hasExplicitClassExpression() { /* XXX: Manually added */
     return hasExplicitClassExpression;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=269e155a5a493e5cbae4fd4f5ea70c1c (do not edit this line) */
