/* Generated By:JJTree: Do not edit this line. ASTObjectFact.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTObjectFact extends SimpleNode {
  public ASTObjectFact(int id) {
    super(id);
  }

  public ASTObjectFact(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=e5df6c0ba19c4f0d954bd8fd4fe78606 (do not edit this line) */
