/* Generated By:JJTree: Do not edit this line. ASTOWLObjectPropertyAssertion.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTObjectPropertyAssertion extends SimpleNode {
  public ASTObjectPropertyAssertion(int id) {
    super(id);
  }

  public ASTObjectPropertyAssertion(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=a233630b354c0addaa707b8fa483a958 (do not edit this line) */
