/* Generated By:JJTree: Do not edit this line. ASTOWLObjectIntersection.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTObjectIntersection extends SimpleNode {
  public ASTObjectIntersection(int id) {
    super(id);
  }

  public ASTObjectIntersection(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=5fbbfcc7f6bcf52c28f377fab98d72b7 (do not edit this line) */
