/* Generated By:JJTree: Do not edit this line. ASTOWLObjectAllValuesFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTObjectAllValuesFrom extends SimpleNode {
  public ASTObjectAllValuesFrom(int id) {
    super(id);
  }

  public ASTObjectAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=82a1981627762d8f0e6b0394b5c9362b (do not edit this line) */
