/* Generated By:JJTree: Do not edit this line. ASTPropertySomeValuesFrom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTPropertySomeValuesFrom extends SimpleNode {
  public ASTPropertySomeValuesFrom(int id) {
    super(id);
  }

  public ASTPropertySomeValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=f842388aad44b5e038ac6e41706c12c8 (do not edit this line) */
