/* Generated By:JJTree: Do not edit this line. ASTPropertyMaxCardinality.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTPropertyMaxCardinality extends SimpleNode {

   public boolean hasFiller; /* XXX: Manually added */

   public ASTPropertyMaxCardinality(int id) {
     super(id);
   }

   public ASTPropertyMaxCardinality(MappingMasterParser p, int id) {
     super(p, id);
   }

   public boolean hasFiller() { /* XXX: Manually added */
     return hasFiller;
   }

   @Override
   public void accept(NodeVisitor visitor) { /* XXX: Manually added */
     visitor.visit(this);
   }
}
/* JavaCC - OriginalChecksum=d5667621953b104f29bdee24bfca4d9b (do not edit this line) */
