/* Generated By:JJTree: Do not edit this line. ASTPropertyAllValuesFrom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTPropertyAllValuesFrom extends SimpleNode {
  public ASTPropertyAllValuesFrom(int id) {
    super(id);
  }

  public ASTPropertyAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=b6ac7eef0cd905e7aa23c68a43c637aa (do not edit this line) */
