/* Generated By:JJTree: Do not edit this line. ASTOWLPropertyAssertions.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTPropertyAssertion extends SimpleNode {
  public ASTPropertyAssertion(int id) {
    super(id);
  }

  public ASTPropertyAssertion(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=f56d880dff1ebd7bfaba5248ab01e8a5 (do not edit this line) */
