/* Generated By:JJTree: Do not edit this line. ASTPropertyHasValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTPropertyHasValue extends SimpleNode {
  public ASTPropertyHasValue(int id) {
    super(id);
  }

  public ASTPropertyHasValue(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=c22c346c1ee6e4fb3db96208cb30eb37 (do not edit this line) */
