/* Generated By:JJTree: Do not edit this line. ASTQName.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTQName extends SimpleNode {

  public String name; /* XXX: Manually added */

  public ASTQName(int id) {
    super(id);
  }

  public ASTQName(MappingMasterParser p, int id) {
    super(p, id);
  }

  public String getValue() { /* XXX: Manually added */
     return name;
   }

   @Override
   public void accept(NodeVisitor visitor) { /* XXX: Manually added */
     visitor.visit(this);
   }
}
/* JavaCC - OriginalChecksum=8a01aac7a3a0ff2bc13f02ac3ef2686e (do not edit this line) */
