/* Generated By:JJTree: Do not edit this line. ASTReferencedSomeValuesFrom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTReferencedSomeValuesFrom extends SimpleNode {
  public ASTReferencedSomeValuesFrom(int id) {
    super(id);
  }

  public ASTReferencedSomeValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=39f9833abf09dca487d94193cef4281b (do not edit this line) */
