/* Generated By:JJTree: Do not edit this line. ASTReferencedAllValuesFrom.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTReferencedAllValuesFrom extends SimpleNode {
  public ASTReferencedAllValuesFrom(int id) {
    super(id);
  }

  public ASTReferencedAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=52397208729724407c7d5a3573df2cc0 (do not edit this line) */
