/* Generated By:JJTree: Do not edit this line. ASTCellLocation.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import javax.annotation.Nonnull; /* XXX: Manually added */

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;
import org.mm.renderer.internal.ReferenceNotation;

public
class ASTReferenceNotation extends SimpleNode {

  ReferenceNotation referenceNotation; /* XXX: Manually added */

  public ASTReferenceNotation(int id) {
    super(id);
  }

  public ASTReferenceNotation(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Nonnull
  public ReferenceNotation getReferenceNotation() { /* XXX: Manually added */
     return referenceNotation;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=ed127b99019758ba3b296af7bc930af4 (do not edit this line) */
