/* Generated By:JJTree: Do not edit this line. ASTOWLRestrictionCategory.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTRestrictionCategory extends SimpleNode {
  public ASTRestrictionCategory(int id) {
    super(id);
  }

  public ASTRestrictionCategory(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=d5ec138afe2524b46588273cda38236c (do not edit this line) */
