/* Generated By:JJTree: Do not edit this line. ASTSourceSpecification.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.MappingMasterParser;
import org.mm.parser.NodeVisitor;

public
class ASTSourceSpecification extends SimpleNode {
  public ASTSourceSpecification(int id) {
    super(id);
  }

  public ASTSourceSpecification(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=488cd25c67bf59588f04b27bf6bb02b3 (do not edit this line) */
