/* Generated By:JJTree: Do not edit this line. ASTUntypedFact.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTUntypedFact extends SimpleNode {
  public ASTUntypedFact(int id) {
    super(id);
  }

  public ASTUntypedFact(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=eecddacdca90092d5d3694d9f63492d8 (do not edit this line) */
