/* Generated By:JJTree: Do not edit this line. ASTUntypedMaxCardinality.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTUntypedMaxCardinality extends SimpleNode {
  public ASTUntypedMaxCardinality(int id) {
    super(id);
  }

  public ASTUntypedMaxCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=6c2aabd388e301467721ec095b839657 (do not edit this line) */
