/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser.node;

import org.mm.parser.*;

public
class ASTValue extends SimpleNode {

  public int valueType; /* XXX: Manually added */

  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(MappingMasterParser p, int id) {
    super(p, id);
  }

  public int getType() { /* XXX: Manually added */
     return valueType;
  }

  @Override
  public void accept(NodeVisitor visitor) { /* XXX: Manually added */
    visitor.visit(this);
  }
}
/* JavaCC - OriginalChecksum=36eb3b24b50fa59222e1435932e9dd4a (do not edit this line) */
