/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 7.0.4 */
package org.mm.parser.node;

import org.mm.parser.*;

public interface MappingMasterParserTreeConstants
{
  public int JJTTRANSFORMATIONRULE = 0;
  public int JJTVOID = 1;
  public int JJTRULEEXPRESSION = 2;
  public int JJTCLASSFRAME = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTSUBCLASSOF = 5;
  public int JJTEQUIVALENTCLASSES = 6;
  public int JJTANNOTATIONASSERTION = 7;
  public int JJTANNOTATION = 8;
  public int JJTANNOTATIONVALUE = 9;
  public int JJTINDIVIDUALFRAME = 10;
  public int JJTINDIVIDUALDECLARATION = 11;
  public int JJTCLASSASSERTION = 12;
  public int JJTPROPERTYASSERTION = 13;
  public int JJTFACT = 14;
  public int JJTPROPERTYFACT = 15;
  public int JJTREFERENCEDFACT = 16;
  public int JJTPROPERTYVALUE = 17;
  public int JJTSAMEAS = 18;
  public int JJTDIFFERENTFROM = 19;
  public int JJTCLASSEXPRESSIONCATEGORY = 20;
  public int JJTCLASS = 21;
  public int JJTOBJECTUNION = 22;
  public int JJTOBJECTINTERSECTION = 23;
  public int JJTOBJECTCOMPLEMENT = 24;
  public int JJTOBJECTONEOF = 25;
  public int JJTPROPERTYEXACTCARDINALITY = 26;
  public int JJTREFERENCEDEXACTCARDINALITY = 27;
  public int JJTPROPERTYMAXCARDINALITY = 28;
  public int JJTREFERENCEDMAXCARDINALITY = 29;
  public int JJTPROPERTYMINCARDINALITY = 30;
  public int JJTREFERENCEDMINCARDINALITY = 31;
  public int JJTCARDINALITYVALUE = 32;
  public int JJTDATAHASVALUE = 33;
  public int JJTOBJECTHASVALUE = 34;
  public int JJTREFERENCEDHASVALUE = 35;
  public int JJTDATAALLVALUESFROM = 36;
  public int JJTOBJECTALLVALUESFROM = 37;
  public int JJTDATASOMEVALUESFROM = 38;
  public int JJTOBJECTSOMEVALUESFROM = 39;
  public int JJTFILLER = 40;
  public int JJTCLASSEXPRESSIONFILLER = 41;
  public int JJTREFERENCEDPROPERTY = 42;
  public int JJTPROPERTY = 43;
  public int JJTDATAPROPERTY = 44;
  public int JJTOBJECTPROPERTY = 45;
  public int JJTANNOTATIONPROPERTY = 46;
  public int JJTNAMEDINDIVIDUAL = 47;
  public int JJTVALUE = 48;
  public int JJTLITERALVALUE = 49;
  public int JJTOBJECTVALUE = 50;
  public int JJTREFERENCE = 51;
  public int JJTNAME = 52;
  public int JJTIRI = 53;
  public int JJTLITERAL = 54;
  public int JJTINTEGERLITERAL = 55;
  public int JJTFLOATLITERAL = 56;
  public int JJTSTRINGLITERAL = 57;
  public int JJTBOOLEANLITERAL = 58;
  public int JJTREFERENCENOTATION = 59;
  public int JJTBUILTINFUNCTION = 60;
  public int JJTARGUMENTLIST = 61;
  public int JJTARGUMENT = 62;
  public int JJTDATATYPE = 63;


  public String[] jjtNodeName = {
    "TransformationRule",
    "void",
    "RuleExpression",
    "ClassFrame",
    "ClassDeclaration",
    "SubclassOf",
    "EquivalentClasses",
    "AnnotationAssertion",
    "Annotation",
    "AnnotationValue",
    "IndividualFrame",
    "IndividualDeclaration",
    "ClassAssertion",
    "PropertyAssertion",
    "Fact",
    "PropertyFact",
    "ReferencedFact",
    "PropertyValue",
    "SameAs",
    "DifferentFrom",
    "ClassExpressionCategory",
    "Class",
    "ObjectUnion",
    "ObjectIntersection",
    "ObjectComplement",
    "ObjectOneOf",
    "PropertyExactCardinality",
    "ReferencedExactCardinality",
    "PropertyMaxCardinality",
    "ReferencedMaxCardinality",
    "PropertyMinCardinality",
    "ReferencedMinCardinality",
    "CardinalityValue",
    "DataHasValue",
    "ObjectHasValue",
    "ReferencedHasValue",
    "DataAllValuesFrom",
    "ObjectAllValuesFrom",
    "DataSomeValuesFrom",
    "ObjectSomeValuesFrom",
    "Filler",
    "ClassExpressionFiller",
    "ReferencedProperty",
    "Property",
    "DataProperty",
    "ObjectProperty",
    "AnnotationProperty",
    "NamedIndividual",
    "Value",
    "LiteralValue",
    "ObjectValue",
    "Reference",
    "Name",
    "Iri",
    "Literal",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "ReferenceNotation",
    "BuiltInFunction",
    "ArgumentList",
    "Argument",
    "Datatype",
  };
}
/* JavaCC - OriginalChecksum=008d243c8e3a60ac50038ff079664acc (do not edit this line) */
