/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 6.1_2 */
package org.mm.parser.node;

public interface MappingMasterParserTreeConstants
{
  public int JJTTRANSFORMATIONRULE = 0;
  public int JJTVOID = 1;
  public int JJTRULEEXPRESSION = 2;
  public int JJTCLASSFRAME = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTSUBCLASSOF = 5;
  public int JJTEQUIVALENTCLASSES = 6;
  public int JJTANNOTATIONASSERTION = 7;
  public int JJTANNOTATION = 8;
  public int JJTINDIVIDUALFRAME = 9;
  public int JJTINDIVIDUALDECLARATION = 10;
  public int JJTCLASSASSERTION = 11;
  public int JJTPROPERTYASSERTION = 12;
  public int JJTFACT = 13;
  public int JJTPROPERTYVALUE = 14;
  public int JJTSAMEAS = 15;
  public int JJTDIFFERENTFROM = 16;
  public int JJTCLASSEXPRESSIONCATEGORY = 17;
  public int JJTCLASS = 18;
  public int JJTOBJECTUNION = 19;
  public int JJTOBJECTINTERSECTION = 20;
  public int JJTOBJECTCOMPLEMENT = 21;
  public int JJTOBJECTONEOF = 22;
  public int JJTDATAEXACTCARDINALITY = 23;
  public int JJTOBJECTEXACTCARDINALITY = 24;
  public int JJTDATAMAXCARDINALITY = 25;
  public int JJTOBJECTMAXCARDINALITY = 26;
  public int JJTDATAMINCARDINALITY = 27;
  public int JJTOBJECTMINCARDINALITY = 28;
  public int JJTDATAHASVALUE = 29;
  public int JJTOBJECTHASVALUE = 30;
  public int JJTDATAALLVALUESFROM = 31;
  public int JJTOBJECTALLVALUESFROM = 32;
  public int JJTDATASOMEVALUESFROM = 33;
  public int JJTOBJECTSOMEVALUESFROM = 34;
  public int JJTPROPERTY = 35;
  public int JJTDATAPROPERTY = 36;
  public int JJTOBJECTPROPERTY = 37;
  public int JJTANNOTATIONPROPERTY = 38;
  public int JJTNAMEDINDIVIDUAL = 39;
  public int JJTVALUECATEGORY = 40;
  public int JJTLITERALVALUE = 41;
  public int JJTOBJECTVALUE = 42;
  public int JJTREFERENCE = 43;
  public int JJTNAME = 44;
  public int JJTQNAME = 45;
  public int JJTIRI = 46;
  public int JJTLITERAL = 47;
  public int JJTINTEGERLITERAL = 48;
  public int JJTFLOATLITERAL = 49;
  public int JJTSTRINGLITERAL = 50;
  public int JJTBOOLEANLITERAL = 51;
  public int JJTREFERENCENOTATION = 52;
  public int JJTBUILTINFUNCTION = 53;
  public int JJTARGUMENT = 54;
  public int JJTREFERENCETYPE = 55;


  public String[] jjtNodeName = {
    "TransformationRule",
    "void",
    "RuleExpression",
    "ClassFrame",
    "ClassDeclaration",
    "SubclassOf",
    "EquivalentClasses",
    "AnnotationAssertion",
    "Annotation",
    "IndividualFrame",
    "IndividualDeclaration",
    "ClassAssertion",
    "PropertyAssertion",
    "Fact",
    "PropertyValue",
    "SameAs",
    "DifferentFrom",
    "ClassExpressionCategory",
    "Class",
    "ObjectUnion",
    "ObjectIntersection",
    "ObjectComplement",
    "ObjectOneOf",
    "DataExactCardinality",
    "ObjectExactCardinality",
    "DataMaxCardinality",
    "ObjectMaxCardinality",
    "DataMinCardinality",
    "ObjectMinCardinality",
    "DataHasValue",
    "ObjectHasValue",
    "DataAllValuesFrom",
    "ObjectAllValuesFrom",
    "DataSomeValuesFrom",
    "ObjectSomeValuesFrom",
    "Property",
    "DataProperty",
    "ObjectProperty",
    "AnnotationProperty",
    "NamedIndividual",
    "ValueCategory",
    "LiteralValue",
    "ObjectValue",
    "Reference",
    "Name",
    "QName",
    "Iri",
    "Literal",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "ReferenceNotation",
    "BuiltInFunction",
    "Argument",
    "ReferenceType",
  };
}
/* JavaCC - OriginalChecksum=7a436bdbe84f9ac3571866acbdd89a5d (do not edit this line) */
