/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 7.0.4 */
package org.mm.parser.node;

import org.mm.parser.*;

public interface MappingMasterParserTreeConstants
{
  public int JJTTRANSFORMATIONRULE = 0;
  public int JJTVOID = 1;
  public int JJTRULEEXPRESSION = 2;
  public int JJTCLASSFRAME = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTSUBCLASSOF = 5;
  public int JJTEQUIVALENTCLASSES = 6;
  public int JJTANNOTATIONASSERTION = 7;
  public int JJTANNOTATION = 8;
  public int JJTANNOTATIONVALUE = 9;
  public int JJTINDIVIDUALFRAME = 10;
  public int JJTINDIVIDUALDECLARATION = 11;
  public int JJTCLASSASSERTION = 12;
  public int JJTPROPERTYASSERTION = 13;
  public int JJTFACT = 14;
  public int JJTDATAFACT = 15;
  public int JJTOBJECTFACT = 16;
  public int JJTUNTYPEDFACT = 17;
  public int JJTSAMEAS = 18;
  public int JJTDIFFERENTFROM = 19;
  public int JJTCLASSEXPRESSIONCATEGORY = 20;
  public int JJTCLASS = 21;
  public int JJTOBJECTUNION = 22;
  public int JJTOBJECTINTERSECTION = 23;
  public int JJTOBJECTCOMPLEMENT = 24;
  public int JJTOBJECTONEOF = 25;
  public int JJTDATAEXACTCARDINALITY = 26;
  public int JJTOBJECTEXACTCARDINALITY = 27;
  public int JJTUNTYPEDEXACTCARDINALITY = 28;
  public int JJTDATAMAXCARDINALITY = 29;
  public int JJTOBJECTMAXCARDINALITY = 30;
  public int JJTUNTYPEDMAXCARDINALITY = 31;
  public int JJTDATAMINCARDINALITY = 32;
  public int JJTOBJECTMINCARDINALITY = 33;
  public int JJTUNTYPEDMINCARDINALITY = 34;
  public int JJTCARDINALITYVALUE = 35;
  public int JJTDATAHASVALUE = 36;
  public int JJTOBJECTHASVALUE = 37;
  public int JJTUNTYPEDHASVALUE = 38;
  public int JJTDATAALLVALUESFROM = 39;
  public int JJTOBJECTALLVALUESFROM = 40;
  public int JJTDATASOMEVALUESFROM = 41;
  public int JJTOBJECTSOMEVALUESFROM = 42;
  public int JJTPROPERTY = 43;
  public int JJTDATAPROPERTY = 44;
  public int JJTOBJECTPROPERTY = 45;
  public int JJTANNOTATIONPROPERTY = 46;
  public int JJTNAMEDINDIVIDUAL = 47;
  public int JJTVALUE = 48;
  public int JJTLITERALVALUE = 49;
  public int JJTOBJECTVALUE = 50;
  public int JJTREFERENCE = 51;
  public int JJTNAME = 52;
  public int JJTIRI = 53;
  public int JJTLITERAL = 54;
  public int JJTINTEGERLITERAL = 55;
  public int JJTFLOATLITERAL = 56;
  public int JJTSTRINGLITERAL = 57;
  public int JJTBOOLEANLITERAL = 58;
  public int JJTREFERENCENOTATION = 59;
  public int JJTBUILTINFUNCTION = 60;
  public int JJTARGUMENTLIST = 61;
  public int JJTARGUMENT = 62;


  public String[] jjtNodeName = {
    "TransformationRule",
    "void",
    "RuleExpression",
    "ClassFrame",
    "ClassDeclaration",
    "SubclassOf",
    "EquivalentClasses",
    "AnnotationAssertion",
    "Annotation",
    "AnnotationValue",
    "IndividualFrame",
    "IndividualDeclaration",
    "ClassAssertion",
    "PropertyAssertion",
    "Fact",
    "DataFact",
    "ObjectFact",
    "UntypedFact",
    "SameAs",
    "DifferentFrom",
    "ClassExpressionCategory",
    "Class",
    "ObjectUnion",
    "ObjectIntersection",
    "ObjectComplement",
    "ObjectOneOf",
    "DataExactCardinality",
    "ObjectExactCardinality",
    "UntypedExactCardinality",
    "DataMaxCardinality",
    "ObjectMaxCardinality",
    "UntypedMaxCardinality",
    "DataMinCardinality",
    "ObjectMinCardinality",
    "UntypedMinCardinality",
    "CardinalityValue",
    "DataHasValue",
    "ObjectHasValue",
    "UntypedHasValue",
    "DataAllValuesFrom",
    "ObjectAllValuesFrom",
    "DataSomeValuesFrom",
    "ObjectSomeValuesFrom",
    "Property",
    "DataProperty",
    "ObjectProperty",
    "AnnotationProperty",
    "NamedIndividual",
    "Value",
    "LiteralValue",
    "ObjectValue",
    "Reference",
    "Name",
    "Iri",
    "Literal",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "ReferenceNotation",
    "BuiltInFunction",
    "ArgumentList",
    "Argument",
  };
}
/* JavaCC - OriginalChecksum=c829b1814796c74390c633d19a8c49c5 (do not edit this line) */
