/* Generated By:JJTree: Do not edit this line. ASTAnnotationFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTAnnotationFact extends SimpleNode {
  public ASTAnnotationFact(int id) {
    super(id);
  }

  public ASTAnnotationFact(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa0dddb5d8750ca18deb33363472f4f5 (do not edit this line) */
