/* Generated By:JJTree: Do not edit this line. ASTAnnotationFact.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTAnnotationFact extends SimpleNode {
  public ASTAnnotationFact(int id) {
    super(id);
  }

  public ASTAnnotationFact(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1711edff836e434fb39ac0bf84e21250 (do not edit this line) */
