/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTBooleanLiteral extends SimpleNode {

  public boolean value = false; /* Manually added */

  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e71ee74fbe4ad308d163ad14ae6719da (do not edit this line) */
