/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTBooleanLiteral extends SimpleNode {
	
  public boolean value = false; /* Manually added */
	
  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0534c0759a499a99e4640832eaf883c2 (do not edit this line) */
