/* Generated By:JJTree: Do not edit this line. ASTDefaultLabel.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLabel extends SimpleNode {

  public String defaultLabel; /* Manually added */

  public ASTDefaultLabel(int id) {
    super(id);
  }

  public ASTDefaultLabel(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e5bb58f094770c08373a2f860c467d8 (do not edit this line) */
