/* Generated By:JJTree: Do not edit this line. ASTDefaultLabel.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLabel extends SimpleNode {

  public String defaultLabel;

  public ASTDefaultLabel(int id) {
    super(id);
  }

  public ASTDefaultLabel(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f29535f3132e137e9e8992dcc40cc279 (do not edit this line) */
