/* Generated By:JJTree: Do not edit this line. ASTDefaultLocationValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLocationValue extends SimpleNode {
	
  public String defaultLocationValue; /* Manually added */

public ASTDefaultLocationValue(int id) {
    super(id);
  }

  public ASTDefaultLocationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3c02d9efb5455ab68e720f467570bb7 (do not edit this line) */
