/* Generated By:JJTree: Do not edit this line. ASTDefaultDataValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultDataValue extends SimpleNode {

  public String defaultDataValue;

  public ASTDefaultDataValue(int id) {
    super(id);
  }

  public ASTDefaultDataValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a8d0efd89a31024601fd146edb90eb2 (do not edit this line) */
