/* Generated By:JJTree: Do not edit this line. ASTDefaultLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLiteral extends SimpleNode {
	
  public String defaultLiteral; /* Manually added */

public ASTDefaultLiteral(int id) {
    super(id);
  }

  public ASTDefaultLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=00637247662e1d063f8997040e553009 (do not edit this line) */
