/* Generated By:JJTree: Do not edit this line. ASTDefaultLocationValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLocationValue extends SimpleNode {

  public String defaultLocationValue; /* Manually added */

  public ASTDefaultLocationValue(int id) {
    super(id);
  }

  public ASTDefaultLocationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=324f95ada38bf9d47a139b2a1bc07091 (do not edit this line) */
