/* Generated By:JJTree: Do not edit this line. ASTDefaultID.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultID extends SimpleNode {

  public String defaultID;

  public ASTDefaultID(int id) {
    super(id);
  }

  public ASTDefaultID(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c3c1c99edb089ae5b150123983d44b2 (do not edit this line) */
