/* Generated By:JJTree: Do not edit this line. ASTDefaultLocationValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTDefaultLocationValue extends SimpleNode {

  public String defaultLocationValue;

  public ASTDefaultLocationValue(int id) {
    super(id);
  }

  public ASTDefaultLocationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85fa3a4466a110401b4910d2151fae2b (do not edit this line) */
