/* Generated By:JJTree: Do not edit this line. ASTEmptyLocationSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyLocationSetting extends SimpleNode {
	
  public int emptyLocationSetting; /* Manually added */

  public ASTEmptyLocationSetting(int id) {
    super(id);
  }

  public ASTEmptyLocationSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c06fb0d5f4444b8db43c0d05a041416b (do not edit this line) */
