/* Generated By:JJTree: Do not edit this line. ASTEmptyLocationSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyLocationSetting extends SimpleNode {

  public int emptyLocationSetting; /* Manually added */

  public ASTEmptyLocationSetting(int id) {
    super(id);
  }

  public ASTEmptyLocationSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebfafa237d6c1b6dfd9796bdaacb7ecd (do not edit this line) */
