/* Generated By:JJTree: Do not edit this line. ASTEmptyRDFSLabelSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyRDFSLabelSetting extends SimpleNode {
	
  public int emptyRDFSLabelSetting; /* Manually added */

public ASTEmptyRDFSLabelSetting(int id) {
    super(id);
  }

  public ASTEmptyRDFSLabelSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b108d4194cd924d9cc7b0681590ba9c3 (do not edit this line) */
