/* Generated By:JJTree: Do not edit this line. ASTEmptyRDFSLabelSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyRDFSLabelSetting extends SimpleNode {

  public int emptyRDFSLabelSetting; /* Manually added */

  public ASTEmptyRDFSLabelSetting(int id) {
    super(id);
  }

  public ASTEmptyRDFSLabelSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7f7687a76491a82887a5618b6321957 (do not edit this line) */
