/* Generated By:JJTree: Do not edit this line. ASTEmptyRDFIDSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyRDFIDSetting extends SimpleNode {

  public int emptyRDFIDSetting;

  public ASTEmptyRDFIDSetting(int id) {
    super(id);
  }

  public ASTEmptyRDFIDSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66959697c84f792133e9d950f5c6f53c (do not edit this line) */
