/* Generated By:JJTree: Do not edit this line. ASTEmptyLiteralSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyLiteralSetting extends SimpleNode {

  public int emptyLiteralSetting; /* Manually added */

  public ASTEmptyLiteralSetting(int id) {
    super(id);
  }

  public ASTEmptyLiteralSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=051de0df9c4f85cd403ae7e1116028f1 (do not edit this line) */
