/* Generated By:JJTree: Do not edit this line. ASTEmptyLiteralSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyLiteralSetting extends SimpleNode {
	
  public int emptyLiteralSetting;  /* Manually added */

public ASTEmptyLiteralSetting(int id) {
    super(id);
  }

  public ASTEmptyLiteralSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3357cf129b17f18a559a865028d49dd8 (do not edit this line) */
