/* Generated By:JJTree: Do not edit this line. ASTEmptyRDFIDSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyRDFIDSetting extends SimpleNode {

  public int emptyRDFIDSetting; /* Manually added */

  public ASTEmptyRDFIDSetting(int id) {
    super(id);
  }

  public ASTEmptyRDFIDSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=98586bdcbc0a25aa5531fc60b0878a01 (do not edit this line) */
