/* Generated By:JJTree: Do not edit this line. ASTEmptyDataValueSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEmptyDataValueSetting extends SimpleNode {

  public int emptyDataValueSetting;

  public ASTEmptyDataValueSetting(int id) {
    super(id);
  }

  public ASTEmptyDataValueSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfa41a15a2e1dc5f873ccc056c54a5e3 (do not edit this line) */
