/* Generated By:JJTree: Do not edit this line. ASTEntityType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTEntityType extends SimpleNode {

  public int entityType;

  public ASTEntityType(int id) {
    super(id);
  }

  public ASTEntityType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3bc5a022c9a0dee35947284fc2d97f7 (do not edit this line) */
