/* Generated By:JJTree: Do not edit this line. ASTFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTFact extends SimpleNode {
  public ASTFact(int id) {
    super(id);
  }

  public ASTFact(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d6ae21c8c940a93a57d89a6e869fc03 (do not edit this line) */
