/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTFloatLiteral extends SimpleNode {

  public float value;

  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10baecc8b85cbf0b0467357c02d9c9a0 (do not edit this line) */
