/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTFloatLiteral extends SimpleNode {
  
  public float value; /* Manually added */

  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27705be0119cb974d11b9830e48e8a8e (do not edit this line) */
