/* Generated By:JJTree: Do not edit this line. ASTIfNotExistsDirective.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIfNotExistsDirective extends SimpleNode {

  public int ifNotExistsSetting; /* Manually added */

  public ASTIfNotExistsDirective(int id) {
    super(id);
  }

  public ASTIfNotExistsDirective(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c52345f3407f131289480b18c45d6a4 (do not edit this line) */
