/* Generated By:JJTree: Do not edit this line. ASTIRIRef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIRIRef extends SimpleNode {
	
  public String value; /* Manually added */
	
  public ASTIRIRef(int id) {
    super(id);
  }

  public ASTIRIRef(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d9d73b5e58d4b1549ca3cdd079540ee (do not edit this line) */
