/* Generated By:JJTree: Do not edit this line. ASTIfExistsDirective.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public class ASTIfExistsDirective extends SimpleNode
{
  public int ifExistsSetting;

  public ASTIfExistsDirective(int id)
  {
    super(id);
  }

  public ASTIfExistsDirective(MappingMasterParser p, int id)
  {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfd47f1e772f5b81dab565d7cdb3a9e5 (do not edit this line) */
