/* Generated By:JJTree: Do not edit this line. ASTIRIRef.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIRIRef extends SimpleNode {

  public String value; /* Manually added */

  public ASTIRIRef(int id) {
    super(id);
  }

  public ASTIRIRef(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3a30f83acb8d18f43471f4dc5483915 (do not edit this line) */
