/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIntegerLiteral extends SimpleNode {
	
  public int value; /* Manually added */
	
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2043fd69b40e753eff9e6892f58b2d0a (do not edit this line) */
