/* Generated By:JJTree: Do not edit this line. ASTIfExistsDirective.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIfExistsDirective extends SimpleNode {
	
  public int ifExistsSetting; /* Manually added */

public ASTIfExistsDirective(int id) {
    super(id);
  }

  public ASTIfExistsDirective(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a6792237537163f584dd83def21ed38 (do not edit this line) */
