/* Generated By:JJTree: Do not edit this line. ASTIRIEncoding.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTIRIEncoding extends SimpleNode {

  public int encodingType; /* Manually added */

  public ASTIRIEncoding(int id) {
    super(id);
  }

  public ASTIRIEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9c3021bf244fdecf3cb0899eaa8708b (do not edit this line) */
