/* Generated By:JJTree: Do not edit this line. ASTLanguage.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTLanguage extends SimpleNode {

  public String language; /* Manually added */

  public ASTLanguage(int id) {
    super(id);
  }

  public ASTLanguage(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=799b9da5292196c2fe2fd2e53e7b30c6 (do not edit this line) */
