/* Generated By:JJTree: Do not edit this line. ASTLanguage.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTLanguage extends SimpleNode {

  public String language;

  public ASTLanguage(int id) {
    super(id);
  }

  public ASTLanguage(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d92fd22f79d75dea8fe095ce9f8ab05 (do not edit this line) */
