/* Generated By:JJTree: Do not edit this line. ASTMMDefaultNamespace.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultNamespace extends SimpleNode {
  
  public String namespace;

  public ASTMMDefaultNamespace(int id) {
    super(id);
  }

  public ASTMMDefaultNamespace(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02d816954f117b2137b79e61b95f33e0 (do not edit this line) */
