/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfExistsSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIfExistsSetting extends SimpleNode {
	
  public int ifExistsSetting; /* Manually added */

public ASTMMDefaultIfExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab55be7fb2aab5a9571101ff76ec2653 (do not edit this line) */
