/* Generated By:JJTree: Do not edit this line. ASTMMDefaultAnnotationPropertyValueType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultAnnotationPropertyValueType extends SimpleNode {
	
  public int defaultType; /* Manually added */

public ASTMMDefaultAnnotationPropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultAnnotationPropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ad7870a8323547250c609480a12862c (do not edit this line) */
