/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyRDFIDSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyRDFIDSetting extends SimpleNode {
	
  public int emptyRDFIDSetting; /* Manually added */

public ASTMMDefaultEmptyRDFIDSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyRDFIDSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96c7c79a67552611b77b83b33947557c (do not edit this line) */
