/* Generated By:JJTree: Do not edit this line. ASTMMDefaultLanguage.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultLanguage extends SimpleNode {
  public ASTMMDefaultLanguage(int id) {
    super(id);
  }

  public ASTMMDefaultLanguage(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4c995b229ec7668164be795ab08ac0b (do not edit this line) */
