/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfNotExistsSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIfNotExistsSetting extends SimpleNode {
	
  public int ifNotExistsSetting; /* Manually added */

public ASTMMDefaultIfNotExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfNotExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a33967f4d541aeb29742e68caace6739 (do not edit this line) */
