/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyLiteralSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyLiteralSetting extends SimpleNode {
	
  public int emptyLiteralSetting; /* Manually added */

public ASTMMDefaultEmptyLiteralSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyLiteralSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b86fffb9825bc21d0afdea680ad325b (do not edit this line) */
