/* Generated By:JJTree: Do not edit this line. ASTMMDefaultPropertyValueType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultPropertyValueType extends SimpleNode {
	
  public int defaultType; /* Manually added */

public ASTMMDefaultPropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultPropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=905cc480305189afcbb84c6796dcf2ab (do not edit this line) */
