/* Generated By:JJTree: Do not edit this line. ASTMMDefaultNamespace.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultNamespace extends SimpleNode {
  public ASTMMDefaultNamespace(int id) {
    super(id);
  }

  public ASTMMDefaultNamespace(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4904e4471422bcc8ef10e10abc3ef699 (do not edit this line) */
