/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIRIEncoding.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIRIEncoding extends SimpleNode {
	
  public int encodingType; /* Manually added */

public ASTMMDefaultIRIEncoding(int id) {
    super(id);
  }

  public ASTMMDefaultIRIEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06084bf502230bc91bc575ef98e81a36 (do not edit this line) */
