/* Generated By:JJTree: Do not edit this line. ASTMMDefaultNamespace.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultNamespace extends SimpleNode {
  public ASTMMDefaultNamespace(int id) {
    super(id);
  }

  public ASTMMDefaultNamespace(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1c76c0bc44d5c617b11434d949cee7e (do not edit this line) */
