/* Generated By:JJTree: Do not edit this line. ASTMMDefaultReferenceType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public class ASTMMDefaultReferenceType extends SimpleNode
{
  public int referenceType;

  public ASTMMDefaultReferenceType(int id)
  {
    super(id);
  }

  public ASTMMDefaultReferenceType(MappingMasterParser p, int id)
  {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e244eac6660cfe52deb26a3160e2944b (do not edit this line) */
