/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyRDFIDSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyRDFIDSetting extends SimpleNode {

  public int emptyRDFIDSetting; /* Manually added */

  public ASTMMDefaultEmptyRDFIDSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyRDFIDSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60dfbc3ecb981f454f02b82d2fbaad79 (do not edit this line) */
