/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfNotExistsSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIfNotExistsSetting extends SimpleNode {

  public int ifNotExistsSetting; /* Manually added */

  public ASTMMDefaultIfNotExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfNotExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=087e4a962e3d0618e0ecb9896ccb047f (do not edit this line) */
