/* Generated By:JJTree: Do not edit this line. ASTMMDefaultPrefix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultPrefix extends SimpleNode {
  public ASTMMDefaultPrefix(int id) {
    super(id);
  }

  public ASTMMDefaultPrefix(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7233f468b85a61740c55710cd44ac714 (do not edit this line) */
