/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIfExistsSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIfExistsSetting extends SimpleNode {

  public int ifExistsSetting; /* Manually added */

  public ASTMMDefaultIfExistsSetting(int id) {
    super(id);
  }

  public ASTMMDefaultIfExistsSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b47f4929185f9fae8a2bd04e9c774a2a (do not edit this line) */
