/* Generated By:JJTree: Do not edit this line. ASTMMDirective.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDirective extends SimpleNode {
  public ASTMMDirective(int id) {
    super(id);
  }

  public ASTMMDirective(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5539a50973658fbdd8c7fcc195764b80 (do not edit this line) */
