/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyLiteralSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyLiteralSetting extends SimpleNode {

  public int emptyLiteralSetting;

  public ASTMMDefaultEmptyLiteralSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyLiteralSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16b5b80b945e9ff3b0e78aeedb59ab74 (do not edit this line) */
