/* Generated By:JJTree: Do not edit this line. ASTMMDefaultShiftSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultShiftSetting extends SimpleNode {
	
  public int shiftSetting; /* Manually added */

public ASTMMDefaultShiftSetting(int id) {
    super(id);
  }

  public ASTMMDefaultShiftSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0f06e3c7e470d26f49f3db79d58ad4d (do not edit this line) */
