/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyRDFSLabelSetting.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyRDFSLabelSetting extends SimpleNode {
	
  public int emptyRDFSLabelSetting; /* Manually added */

public ASTMMDefaultEmptyRDFSLabelSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyRDFSLabelSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c15bc3a05aa47f653cee2f5726deab74 (do not edit this line) */
