/* Generated By:JJTree: Do not edit this line. ASTMMDefaultValueEncoding.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultValueEncoding extends SimpleNode {
  public int encodingType;

public ASTMMDefaultValueEncoding(int id) {
    super(id);
  }

  public ASTMMDefaultValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f17ab6ddb1b25462e90ef5dc6aae42fa (do not edit this line) */
