/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyRDFIDSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyRDFIDSetting extends SimpleNode {

  public int emptyRDFIDSetting;

  public ASTMMDefaultEmptyRDFIDSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyRDFIDSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68da9af1099a6fc950ddfec362591fba (do not edit this line) */
