/* Generated By:JJTree: Do not edit this line. ASTMMDefaultDatatypePropertyValueType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultDatatypePropertyValueType extends SimpleNode {

  public int defaultType; /* Manually added */

  public ASTMMDefaultDatatypePropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultDatatypePropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3677aa5053b1e3bfe17b0f0a69b27983 (do not edit this line) */
