/* Generated By:JJTree: Do not edit this line. ASTMMDefaultIRIEncoding.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultIRIEncoding extends SimpleNode {

  public int encodingType; /* Manually added */

  public ASTMMDefaultIRIEncoding(int id) {
    super(id);
  }

  public ASTMMDefaultIRIEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad23ff4da7c23749d61672b76a969243 (do not edit this line) */
