/* Generated By:JJTree: Do not edit this line. ASTMMDefaultEmptyLocationSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultEmptyLocationSetting extends SimpleNode {

  public int emptyLocationSetting; /* Manually added */

  public ASTMMDefaultEmptyLocationSetting(int id) {
    super(id);
  }

  public ASTMMDefaultEmptyLocationSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da04c59bd486939e648b55ed429f8477 (do not edit this line) */
