/* Generated By:JJTree: Do not edit this line. ASTMMDefaultValueEncoding.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultValueEncoding extends SimpleNode {

  public int encodingType; /* Manually added */

  public ASTMMDefaultValueEncoding(int id) {
    super(id);
  }

  public ASTMMDefaultValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=158b506c1afa89b7480acbe262752893 (do not edit this line) */
