/* Generated By:JJTree: Do not edit this line. ASTMMDefaultReferenceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultReferenceType extends SimpleNode {
  public ASTMMDefaultReferenceType(int id) {
    super(id);
  }

  public ASTMMDefaultReferenceType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efc91106e70049375bb4c073aa71d13d (do not edit this line) */
