/* Generated By:JJTree: Do not edit this line. ASTMMDefaultShiftSetting.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultShiftSetting extends SimpleNode {

  public int shiftSetting; /* Manually added */

  public ASTMMDefaultShiftSetting(int id) {
    super(id);
  }

  public ASTMMDefaultShiftSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=291975a45980f973d06f6718772b4c26 (do not edit this line) */
