/* Generated By:JJTree: Do not edit this line. ASTMMExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMExpression extends SimpleNode {
  public ASTMMExpression(int id) {
    super(id);
  }

  public ASTMMExpression(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e9567a923eb2176bdf1a2a51cc9eca8d (do not edit this line) */
