/* Generated By:JJTree: Do not edit this line. ASTMMDefaultAnnotationPropertyValueType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultAnnotationPropertyValueType extends SimpleNode {

  public int defaultType; /* Manually added */

  public ASTMMDefaultAnnotationPropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultAnnotationPropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b388067599f65a22adfbcc3eb8f13a6 (do not edit this line) */
