/* Generated By:JJTree: Do not edit this line. ASTMMDefaultLanguage.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultLanguage extends SimpleNode {
  public ASTMMDefaultLanguage(int id) {
    super(id);
  }

  public ASTMMDefaultLanguage(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5643d3c1e4cb210e0675290a9060ba45 (do not edit this line) */
