/* Generated By:JJTree: Do not edit this line. ASTMMDefaultPropertyType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultPropertyType extends SimpleNode {
	
  public int defaultType; /* Manually added */

public ASTMMDefaultPropertyType(int id) {
    super(id);
  }

  public ASTMMDefaultPropertyType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9f14a22759375db3c802bc95734a29c (do not edit this line) */
