/* Generated By:JJTree: Do not edit this line. ASTMMDefaultPropertyValueType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTMMDefaultPropertyValueType extends SimpleNode {

  public int defaultType; /* Manually added */

  public ASTMMDefaultPropertyValueType(int id) {
    super(id);
  }

  public ASTMMDefaultPropertyValueType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f37332044c4039095edcc5cde130ce4 (do not edit this line) */
