/* Generated By:JJTree: Do not edit this line. ASTName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTName extends SimpleNode {
	
  public String name; /* Manually added */
  public boolean isQuotedName;  /* Manually added */

public ASTName(int id) {
    super(id);
  }

  public ASTName(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=177791e46025a082a331367e72c25233 (do not edit this line) */
