/* Generated By:JJTree: Do not edit this line. ASTNamespace.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTNamespace extends SimpleNode {

  public String namespace;

  public ASTNamespace(int id) {
    super(id);
  }

  public ASTNamespace(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04502fa396eb59632692b066c099941a (do not edit this line) */
