/* Generated By:JJTree: Do not edit this line. ASTName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTName extends SimpleNode {

  public String name;
  public boolean isQuotedName;

  public ASTName(int id) {
    super(id);
  }

  public ASTName(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7bc8650cc11344c66991c3efc4261b4e (do not edit this line) */
