/* Generated By:JJTree: Do not edit this line. ASTNamespace.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTNamespace extends SimpleNode {

  public String namespace; /* Manually added */

  public ASTNamespace(int id) {
    super(id);
  }

  public ASTNamespace(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f05ecc016d56797c1e4b01bdce03ae11 (do not edit this line) */
