/* Generated By:JJTree: Do not edit this line. ASTOWLUnionClass.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLUnionClass extends SimpleNode {
  public ASTOWLUnionClass(int id) {
    super(id);
  }

  public ASTOWLUnionClass(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81ca305c9889a8955afeb19ec931382a (do not edit this line) */
