/* Generated By:JJTree: Do not edit this line. ASTOWLObjectOneOf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectOneOf extends SimpleNode {
  public ASTOWLObjectOneOf(int id) {
    super(id);
  }

  public ASTOWLObjectOneOf(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6030cb6fb83f123145bd321ce330d73a (do not edit this line) */
