/* Generated By:JJTree: Do not edit this line. ASTOWLMaxCardinality.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLMaxCardinality extends SimpleNode {

  public int cardinality;

  public ASTOWLMaxCardinality(int id) {
    super(id);
  }

  public ASTOWLMaxCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=874382e5625698b75bb0d766c918eb5b (do not edit this line) */
