/* Generated By:JJTree: Do not edit this line. ASTOWLDifferentFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDifferentFrom extends SimpleNode {
  public ASTOWLDifferentFrom(int id) {
    super(id);
  }

  public ASTOWLDifferentFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0238a1584e2af5497a3a2e74263f28b1 (do not edit this line) */
