/* Generated By:JJTree: Do not edit this line. ASTOWLSomeValuesFromRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLSomeValuesFromRestriction extends SimpleNode {
  public ASTOWLSomeValuesFromRestriction(int id) {
    super(id);
  }

  public ASTOWLSomeValuesFromRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89ea288d0ffde95b7f913582aeeddb00 (do not edit this line) */
