/* Generated By:JJTree: Do not edit this line. ASTOWLSubclassOf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLSubclassOf extends SimpleNode {
  public ASTOWLSubclassOf(int id) {
    super(id);
  }

  public ASTOWLSubclassOf(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9ef98c8852ac5033ec4f20d8b818def (do not edit this line) */
