/* Generated By:JJTree: Do not edit this line. ASTOWLEquivalentClasses.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLEquivalentClasses extends SimpleNode {
  public ASTOWLEquivalentClasses(int id) {
    super(id);
  }

  public ASTOWLEquivalentClasses(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a9c957849d249aa884f7b747540c713 (do not edit this line) */
