/* Generated By:JJTree: Do not edit this line. ASTOWLRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLRestriction extends SimpleNode {
  public ASTOWLRestriction(int id) {
    super(id);
  }

  public ASTOWLRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d5768e66adfaa13ba78a329a5e97ca0 (do not edit this line) */
