/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationValue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLAnnotationValue extends SimpleNode {
  public ASTOWLAnnotationValue(int id) {
    super(id);
  }

  public ASTOWLAnnotationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc9a90af4c0152781f23f96b8229ba03 (do not edit this line) */
