/* Generated By:JJTree: Do not edit this line. ASTOWLLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLLiteral extends SimpleNode {
  public ASTOWLLiteral(int id) {
    super(id);
  }

  public ASTOWLLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90bd5d4fa4f28aa056607c0e26300d7a (do not edit this line) */
