/* Generated By:JJTree: Do not edit this line. ASTOWLProperty.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLProperty extends SimpleNode {
  public ASTOWLProperty(int id) {
    super(id);
  }

  public ASTOWLProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd9cbf863adedec14fbcab0daa5f830a (do not edit this line) */
