/* Generated By:JJTree: Do not edit this line. ASTOWLClass.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLClass extends SimpleNode {
  public ASTOWLClass(int id) {
    super(id);
  }

  public ASTOWLClass(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5e221e493bf84326a0330fa71cee372 (do not edit this line) */
