/* Generated By:JJTree: Do not edit this line. ASTOWLIntersectionClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLIntersectionClass extends SimpleNode {
  public ASTOWLIntersectionClass(int id) {
    super(id);
  }

  public ASTOWLIntersectionClass(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ca8b7a810b6e0b232fc53d11d7af67e (do not edit this line) */
