/* Generated By:JJTree: Do not edit this line. ASTOWLObjectSomeValuesFrom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectSomeValuesFrom extends SimpleNode {
  public ASTOWLObjectSomeValuesFrom(int id) {
    super(id);
  }

  public ASTOWLObjectSomeValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17649552792adc490ce5835efc54f137 (do not edit this line) */
