/* Generated By:JJTree: Do not edit this line. ASTOWLObjectProperty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectProperty extends SimpleNode {
  public ASTOWLObjectProperty(int id) {
    super(id);
  }

  public ASTOWLObjectProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2970390b29e519c8ead0c41905e34b16 (do not edit this line) */
