/* Generated By:JJTree: Do not edit this line. ASTOWLExactCardinalityRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLExactCardinalityRestriction extends SimpleNode {

  public int cardinality; /* Manually added */

  public ASTOWLExactCardinalityRestriction(int id) {
    super(id);
  }

  public ASTOWLExactCardinalityRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2aec8c23d6403c5b630b47b9a29c6bc8 (do not edit this line) */
