/* Generated By:JJTree: Do not edit this line. ASTOWLDataAllValuesFrom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDataAllValuesFrom extends SimpleNode {
	
  public int datatype;  /* Manually added */

public ASTOWLDataAllValuesFrom(int id) {
    super(id);
  }

  public ASTOWLDataAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2eed7a51d4a3039b9c9bad607bc326e (do not edit this line) */
