/* Generated By:JJTree: Do not edit this line. ASTOWLHasValueRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLHasValueRestriction extends SimpleNode {
  public ASTOWLHasValueRestriction(int id) {
    super(id);
  }

  public ASTOWLHasValueRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0fa9ea5c81a03fb9993f6a6001f0aede (do not edit this line) */
