/* Generated By:JJTree: Do not edit this line. ASTOWLProperty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLProperty extends SimpleNode {
  public ASTOWLProperty(int id) {
    super(id);
  }

  public ASTOWLProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d842092386e1b10b6673942bfc39a322 (do not edit this line) */
