/* Generated By:JJTree: Do not edit this line. ASTOWLNamedIndividual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLNamedIndividual extends SimpleNode {
  public ASTOWLNamedIndividual(int id) {
    super(id);
  }

  public ASTOWLNamedIndividual(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2161d0d1e49f569724f45bb42162c586 (do not edit this line) */
