/* Generated By:JJTree: Do not edit this line. ASTOWLSomeValuesFromRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLSomeValuesFromRestriction extends SimpleNode {
  public ASTOWLSomeValuesFromRestriction(int id) {
    super(id);
  }

  public ASTOWLSomeValuesFromRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=262820724607efe03f1a599743b416a8 (do not edit this line) */
