/* Generated By:JJTree: Do not edit this line. ASTOWLExactCardinalityRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLExactCardinalityRestriction extends SimpleNode {
	
  public int cardinality;  /* Manually added */

public ASTOWLExactCardinalityRestriction(int id) {
    super(id);
  }

  public ASTOWLExactCardinalityRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad3c3240a3bfbe8a0215aa93a0ed2e57 (do not edit this line) */
