/* Generated By:JJTree: Do not edit this line. ASTOWLCardinality.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLCardinality extends SimpleNode {

  public int cardinality;

  public ASTOWLCardinality(int id) {
    super(id);
  }

  public ASTOWLCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b58744048161c3b9b673d24b068c8f25 (do not edit this line) */
