/* Generated By:JJTree: Do not edit this line. ASTOWLMaxCardinalityRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLMaxCardinalityRestriction extends SimpleNode {
	public int cardinality;

	public ASTOWLMaxCardinalityRestriction(int id) {
		super(id);
	}

	public ASTOWLMaxCardinalityRestriction(MappingMasterParser p, int id) {
		super(p, id);
	}

}
/* JavaCC - OriginalChecksum=ebbf4b12b5570bea7f5133fd15d72907 (do not edit this line) */
