/* Generated By:JJTree: Do not edit this line. ASTOWLMinCardinality.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLMinCardinality extends SimpleNode {

  public int cardinality;

  public ASTOWLMinCardinality(int id) {
    super(id);
  }

  public ASTOWLMinCardinality(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e0e48a95725d8f6538203a59a338880 (do not edit this line) */
