/* Generated By:JJTree: Do not edit this line. ASTOWLClassExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLClassExpression extends SimpleNode {
	
  public boolean isNegated;  /* Manually added */

public ASTOWLClassExpression(int id) {
    super(id);
  }

  public ASTOWLClassExpression(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=315cab657387180d6968b52b42aca53d (do not edit this line) */
