/* Generated By:JJTree: Do not edit this line. ASTOWLDataSomeValuesFrom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDataSomeValuesFrom extends SimpleNode {
	
  public int datatype;  /* Manually added */

public ASTOWLDataSomeValuesFrom(int id) {
    super(id);
  }

  public ASTOWLDataSomeValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=367515669733ea8bb32c9db5530a38fc (do not edit this line) */
