/* Generated By:JJTree: Do not edit this line. ASTOWLDataAllValuesFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDataAllValuesFrom extends SimpleNode {

  public int datatype; /* Manually added */

  public ASTOWLDataAllValuesFrom(int id) {
    super(id);
  }

  public ASTOWLDataAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b945a19b07757e145ee99a4f1918157 (do not edit this line) */
