/* Generated By:JJTree: Do not edit this line. ASTOWLObjectSomeValuesFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectSomeValuesFrom extends SimpleNode {
  public ASTOWLObjectSomeValuesFrom(int id) {
    super(id);
  }

  public ASTOWLObjectSomeValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2d28289cffa9827dee6e258fab2a6f4 (do not edit this line) */
