/* Generated By:JJTree: Do not edit this line. ASTOWLClassDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLClassDeclaration extends SimpleNode {
  public ASTOWLClassDeclaration(int id) {
    super(id);
  }

  public ASTOWLClassDeclaration(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=467b7a1c1357ccf8e670f20980d7f86c (do not edit this line) */
