/* Generated By:JJTree: Do not edit this line. ASTOWLHasValueRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLHasValueRestriction extends SimpleNode {
  public ASTOWLHasValueRestriction(int id) {
    super(id);
  }

  public ASTOWLHasValueRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7464c58e4d8c7b5720f241d30436b89d (do not edit this line) */
