/* Generated By:JJTree: Do not edit this line. ASTOWLObjectPropertyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectPropertyDeclaration extends SimpleNode {
  public ASTOWLObjectPropertyDeclaration(int id) {
    super(id);
  }

  public ASTOWLObjectPropertyDeclaration(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44034a1d9b75e69def2abcde641a3634 (do not edit this line) */
