/* Generated By:JJTree: Do not edit this line. ASTOWLMinCardinalityRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLMinCardinalityRestriction extends SimpleNode {
	
  public int cardinality;  /* Manually added */

public ASTOWLMinCardinalityRestriction(int id) {
    super(id);
  }

  public ASTOWLMinCardinalityRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec9411faa6fe39f084b0a443e0541ffa (do not edit this line) */
