/* Generated By:JJTree: Do not edit this line. ASTOWLSameAs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLSameAs extends SimpleNode {
  public ASTOWLSameAs(int id) {
    super(id);
  }

  public ASTOWLSameAs(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57e787f68caf9e702d46722ec36c3504 (do not edit this line) */
