/* Generated By:JJTree: Do not edit this line. ASTOWLClassExpression.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLClassExpression extends SimpleNode {

  public boolean isNegated; /* Manually added */

  public ASTOWLClassExpression(int id) {
    super(id);
  }

  public ASTOWLClassExpression(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d0db9ae44bc24f3feef518f80ab0540 (do not edit this line) */
