/* Generated By:JJTree: Do not edit this line. ASTOWLPropertyAssertionObject.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLPropertyAssertionObject extends SimpleNode {
  public ASTOWLPropertyAssertionObject(int id) {
    super(id);
  }

  public ASTOWLPropertyAssertionObject(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bcc6f0ab50ea63c20b8d9f8bf882d74 (do not edit this line) */
