/* Generated By:JJTree: Do not edit this line. ASTOWLObjectOneOf.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectOneOf extends SimpleNode {
  public ASTOWLObjectOneOf(int id) {
    super(id);
  }

  public ASTOWLObjectOneOf(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9fd47cf6b3f06440f67572b41a3f79e (do not edit this line) */
