/* Generated By:JJTree: Do not edit this line. ASTOWLIndividualDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLIndividualDeclaration extends SimpleNode {
  public ASTOWLIndividualDeclaration(int id) {
    super(id);
  }

  public ASTOWLIndividualDeclaration(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b459f5610987e6a3c288e42c6b1328cd (do not edit this line) */
