/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationProperty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLAnnotationProperty extends SimpleNode {
  public ASTOWLAnnotationProperty(int id) {
    super(id);
  }

  public ASTOWLAnnotationProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a78df08e7b20a1e2fbf27e5e22c3687 (do not edit this line) */
