/* Generated By:JJTree: Do not edit this line. ASTOWLObjectAllValuesFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLObjectAllValuesFrom extends SimpleNode {
  public ASTOWLObjectAllValuesFrom(int id) {
    super(id);
  }

  public ASTOWLObjectAllValuesFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82a1981627762d8f0e6b0394b5c9362b (do not edit this line) */
