/* Generated By:JJTree: Do not edit this line. ASTOWLSubclassOf.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLSubclassOf extends SimpleNode {
  public ASTOWLSubclassOf(int id) {
    super(id);
  }

  public ASTOWLSubclassOf(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=154e072f46e26d0d641bec95e98bcb26 (do not edit this line) */
