/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLAnnotationValue extends SimpleNode {
  public ASTOWLAnnotationValue(int id) {
    super(id);
  }

  public ASTOWLAnnotationValue(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fff12cbe23c929824086b0d64e29fa13 (do not edit this line) */
