/* Generated By:JJTree: Do not edit this line. ASTOWLMinCardinalityRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public class ASTOWLMinCardinalityRestriction extends SimpleNode
{
	public int cardinality;

	public ASTOWLMinCardinalityRestriction(int id)
	{
		super(id);
	}

	public ASTOWLMinCardinalityRestriction(MappingMasterParser p, int id)
	{
		super(p, id);
	}

}
/* JavaCC - OriginalChecksum=d0860c586965cfc5f6730a6f47f58500 (do not edit this line) */
