/* Generated By:JJTree: Do not edit this line. ASTOWLIntersectionClass.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLIntersectionClass extends SimpleNode {
  public ASTOWLIntersectionClass(int id) {
    super(id);
  }

  public ASTOWLIntersectionClass(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=07c7a6f216d6884b7650dd0882d85cb7 (do not edit this line) */
