/* Generated By:JJTree: Do not edit this line. ASTOWLDataSomeValuesFrom.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDataSomeValuesFrom extends SimpleNode {
	public int datatype;

	public ASTOWLDataSomeValuesFrom(int id) {
		super(id);
	}

	public ASTOWLDataSomeValuesFrom(MappingMasterParser p, int id) {
		super(p, id);
	}

}
/* JavaCC - OriginalChecksum=cbe998b4e18bd38a5906469000bbe6d2 (do not edit this line) */
