/* Generated By:JJTree: Do not edit this line. ASTOWLNamedEntityName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLNamedEntityName extends SimpleNode {

  public String entityName;

  public ASTOWLNamedEntityName(int id) {
    super(id);
  }

  public ASTOWLNamedEntityName(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92d7af7a61c3eff03416a4ae9632795c (do not edit this line) */
