/* Generated By:JJTree: Do not edit this line. ASTOWLMaxCardinalityRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLMaxCardinalityRestriction extends SimpleNode {
	
  public int cardinality;  /* Manually added */

public ASTOWLMaxCardinalityRestriction(int id) {
    super(id);
  }

  public ASTOWLMaxCardinalityRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1a135ce770d31dde70e0376d43459b9 (do not edit this line) */
