/* Generated By:JJTree: Do not edit this line. ASTOWLAnnotationProperty.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLAnnotationProperty extends SimpleNode {
  public ASTOWLAnnotationProperty(int id) {
    super(id);
  }

  public ASTOWLAnnotationProperty(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90572760ad8f5486fc48afc2643202dd (do not edit this line) */
