/* Generated By:JJTree: Do not edit this line. ASTOWLAllValuesFromRestriction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLAllValuesFromRestriction extends SimpleNode {
  public ASTOWLAllValuesFromRestriction(int id) {
    super(id);
  }

  public ASTOWLAllValuesFromRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d0342acd580db38ab3e5f5ea0b60ac3 (do not edit this line) */
