/* Generated By:JJTree: Do not edit this line. ASTOWLIndividualDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLIndividualDeclaration extends SimpleNode {
  public ASTOWLIndividualDeclaration(int id) {
    super(id);
  }

  public ASTOWLIndividualDeclaration(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=153d4f571d649882b7b81794f9e0d596 (do not edit this line) */
