/* Generated By:JJTree: Do not edit this line. ASTOWLRestriction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLRestriction extends SimpleNode {
  public ASTOWLRestriction(int id) {
    super(id);
  }

  public ASTOWLRestriction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2b881d6bc0355abf169c7f877fc5778 (do not edit this line) */
