/* Generated By:JJTree: Do not edit this line. ASTOWLDifferentFrom.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTOWLDifferentFrom extends SimpleNode {
  public ASTOWLDifferentFrom(int id) {
    super(id);
  }

  public ASTOWLDifferentFrom(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=587384f69fa5cbe09371219f644be22a (do not edit this line) */
