/* Generated By:JJTree: Do not edit this line. ASTPrefix.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTPrefix extends SimpleNode {

  public String prefix; /* Manually added */

  public ASTPrefix(int id) {
    super(id);
  }

  public ASTPrefix(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e7b56aaeab2e727b8ba842fe03ae9b9 (do not edit this line) */
