/* Generated By:JJTree: Do not edit this line. ASTPrefix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTPrefix extends SimpleNode {
	
  public String prefix; /* Manually added */

public ASTPrefix(int id) {
    super(id);
  }

  public ASTPrefix(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=023ff68bc17b9b95afc6574d35108923 (do not edit this line) */
