/* Generated By:JJTree: Do not edit this line. ASTReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTReference extends SimpleNode {
	
  public DefaultReferenceDirectives defaultReferenceDirectives;  /* Manually added */

public ASTReference(int id) {
    super(id);
  }

  public ASTReference(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c4e01ee9307a75333f4eb9a9962856c (do not edit this line) */
