/* Generated By:JJTree: Do not edit this line. ASTReference.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTReference extends SimpleNode {

  public DefaultReferenceDirectives defaultReferenceDirectives; /* Manually added */

  public ASTReference(int id) {
    super(id);
  }

  public ASTReference(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9ef9dc174d09ff7bc13bfe6b966a6cd (do not edit this line) */
