/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTReferenceType extends SimpleNode {

  public int referenceType;

  public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe047446cb65ed2a610d6b4570ac2975 (do not edit this line) */
