/* Generated By:JJTree: Do not edit this line. ASTReference.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTReference extends SimpleNode {

  public DefaultReferenceDirectives defaultReferenceDirectives;

	public ASTReference(int id) {
    super(id);
  }

  public ASTReference(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7559d2502094081e8f52322139c3a5c4 (do not edit this line) */
