/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTReferenceType extends SimpleNode {
	
  public int referenceType;  /* Manually added */

public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b537556f612c7dda89c9a8563783861d (do not edit this line) */
