/* Generated By:JJTree: Do not edit this line. ASTShiftSetting.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTShiftSetting extends SimpleNode {
	
	public int shiftSetting;
	
  public ASTShiftSetting(int id) {
    super(id);
  }

  public ASTShiftSetting(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ba8b47d86891751ae4f11caba2d4f60 (do not edit this line) */
