/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTStringLiteral extends SimpleNode {

  public String value;

  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5acf4439a8d0063d3b0fc76dd75e1a3b (do not edit this line) */
