/* Generated By:JJTree: Do not edit this line. ASTSourceSpecification.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTSourceSpecification extends SimpleNode {

  public String source; /* Manually added */
  public String location; /* Manually added */
  public String literal; /* Manually added */

public ASTSourceSpecification(int id) {
    super(id);
  }

  public ASTSourceSpecification(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=488cd25c67bf59588f04b27bf6bb02b3 (do not edit this line) */
