/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTStringLiteral extends SimpleNode {

  public String value; /* Manually added */

  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f0bbbf673d8fff9a83c127b277d94ced (do not edit this line) */
