/* Generated By:JJTree: Do not edit this line. ASTSourceSpecification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public class ASTSourceSpecification extends SimpleNode {

	public String source; /* Manually added */
	public String location; /* Manually added */
	public String literal;  /* Manually added */

	public ASTSourceSpecification(int id) {
		super(id);
	}

	public ASTSourceSpecification(MappingMasterParser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=68fceb2b853b3afca5f72b39cf4691f5 (do not edit this
 * line)
 */
