/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTStringLiteral extends SimpleNode {
	
  public String value; /* Manually added */
	
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62e8977830910fd94b13d1d36b543797 (do not edit this line) */
