/* Generated By:JJTree: Do not edit this line. ASTTypes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTTypes extends SimpleNode {
  public ASTTypes(int id) {
    super(id);
  }

  public ASTTypes(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcc435cb41661944fbc695f2a468a66a (do not edit this line) */
