/* Generated By:JJTree: Do not edit this line. ASTTypes.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTTypes extends SimpleNode {
  public ASTTypes(int id) {
    super(id);
  }

  public ASTTypes(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca722d55809e35c5dc564484a23bdb63 (do not edit this line) */
