/* Generated By:JJTree: Do not edit this line. ASTValueExtractionFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueExtractionFunction extends SimpleNode {

  public int functionID;

  public ASTValueExtractionFunction(int id) {
    super(id);
  }

  public ASTValueExtractionFunction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0053d069d7d30b922a26ef31ffe5d293 (do not edit this line) */
