/* Generated By:JJTree: Do not edit this line. ASTValueEncoding.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueEncoding extends SimpleNode {

  public int encodingType; /* Manually added */

  public ASTValueEncoding(int id) {
    super(id);
  }

  public ASTValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4b5cc8c312250751821405fd54862a7 (do not edit this line) */
