/* Generated By:JJTree: Do not edit this line. ASTValueExtractionFunctionArgument.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueExtractionFunctionArgument extends SimpleNode {
  public ASTValueExtractionFunctionArgument(int id) {
    super(id);
  }

  public ASTValueExtractionFunctionArgument(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7daf23f171678d76c367b8a0956f78ba (do not edit this line) */
