/* Generated By:JJTree: Do not edit this line. ASTValueSpecification.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueSpecification extends SimpleNode {
  public ASTValueSpecification(int id) {
    super(id);
  }

  public ASTValueSpecification(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e14df5a505b3041795b62b135cafa9c7 (do not edit this line) */
