/* Generated By:JJTree: Do not edit this line. ASTValueExtractionFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueExtractionFunction extends SimpleNode {
	
  public int functionID; /* Manually added */

public ASTValueExtractionFunction(int id) {
    super(id);
  }

  public ASTValueExtractionFunction(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e16c57a6de74e2d4fee04b5220422af (do not edit this line) */
