/* Generated By:JJTree: Do not edit this line. ASTValueExtractionFunctionArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueExtractionFunctionArgument extends SimpleNode {
  public ASTValueExtractionFunctionArgument(int id) {
    super(id);
  }

  public ASTValueExtractionFunctionArgument(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7cbd3890fb39b8dcefd560ad50dcbe1 (do not edit this line) */
