/* Generated By:JJTree: Do not edit this line. ASTValueSpecification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueSpecification extends SimpleNode {
  public ASTValueSpecification(int id) {
    super(id);
  }

  public ASTValueSpecification(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bbe1b4227f357c9242a5833bb8f8ef7 (do not edit this line) */
