/* Generated By:JJTree: Do not edit this line. ASTValueSpecificationItem.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueSpecificationItem extends SimpleNode {

  public String stringLiteral;
  public String captureExpression;

  public ASTValueSpecificationItem(int id) {
    super(id);
  }

  public ASTValueSpecificationItem(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c759916646326444811e0c4ce45a9048 (do not edit this line) */
