/* Generated By:JJTree: Do not edit this line. ASTValueSpecificationItem.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueSpecificationItem extends SimpleNode {

  public String stringLiteral; /* Manually added */
  public String captureExpression; /* Manually added */

public ASTValueSpecificationItem(int id) {
    super(id);
  }

  public ASTValueSpecificationItem(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9876c3ae578f58e5acb459ee749bc01 (do not edit this line) */
