/* Generated By:JJTree: Do not edit this line. ASTValueEncoding.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.mm.parser;

public
class ASTValueEncoding extends SimpleNode {
	
  public int encodingType;  /* Manually added */

public ASTValueEncoding(int id) {
    super(id);
  }

  public ASTValueEncoding(MappingMasterParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ccfec1d65ad356eeaabf20054684fb7d (do not edit this line) */
