/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 5.0 */
package org.mm.parser;

public interface MappingMasterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTMMDIRECTIVE = 1;
  public int JJTMMEXPRESSION = 2;
  public int JJTMMDEFAULTVALUEENCODING = 3;
  public int JJTMMDEFAULTIRIENCODING = 4;
  public int JJTMMDEFAULTSHIFTSETTING = 5;
  public int JJTMMDEFAULTEMPTYLOCATIONSETTING = 6;
  public int JJTMMDEFAULTEMPTYLITERALSETTING = 7;
  public int JJTMMDEFAULTIFEXISTSSETTING = 8;
  public int JJTMMDEFAULTIFNOTEXISTSSETTING = 9;
  public int JJTMMDEFAULTEMPTYRDFIDSETTING = 10;
  public int JJTMMDEFAULTEMPTYRDFSLABELSETTING = 11;
  public int JJTMMDEFAULTREFERENCETYPE = 12;
  public int JJTMMDEFAULTLANGUAGE = 13;
  public int JJTMMDEFAULTPREFIX = 14;
  public int JJTMMDEFAULTNAMESPACE = 15;
  public int JJTMMDEFAULTPROPERTYVALUETYPE = 16;
  public int JJTMMDEFAULTDATATYPEPROPERTYVALUETYPE = 17;
  public int JJTMMDEFAULTANNOTATIONPROPERTYVALUETYPE = 18;
  public int JJTMMDEFAULTPROPERTYTYPE = 19;
  public int JJTOWLCLASSDECLARATION = 20;
  public int JJTOWLOBJECTPROPERTYDECLARATION = 21;
  public int JJTOWLEQUIVALENTCLASSES = 22;
  public int JJTOWLSUBCLASSOF = 23;
  public int JJTOWLINDIVIDUALDECLARATION = 24;
  public int JJTOWLSAMEAS = 25;
  public int JJTOWLDIFFERENTFROM = 26;
  public int JJTVOID = 27;
  public int JJTFACT = 28;
  public int JJTANNOTATIONFACT = 29;
  public int JJTOWLANNOTATIONPROPERTY = 30;
  public int JJTNAME = 31;
  public int JJTOWLANNOTATIONVALUE = 32;
  public int JJTOWLLITERAL = 33;
  public int JJTINTEGERLITERAL = 34;
  public int JJTFLOATLITERAL = 35;
  public int JJTSTRINGLITERAL = 36;
  public int JJTBOOLEANLITERAL = 37;
  public int JJTIRIREF = 38;
  public int JJTOWLCLASSEXPRESSION = 39;
  public int JJTOWLUNIONCLASS = 40;
  public int JJTOWLINTERSECTIONCLASS = 41;
  public int JJTOWLOBJECTONEOF = 42;
  public int JJTOWLCLASS = 43;
  public int JJTOWLOBJECTPROPERTY = 44;
  public int JJTOWLNAMEDINDIVIDUAL = 45;
  public int JJTOWLPROPERTY = 46;
  public int JJTTYPES = 47;
  public int JJTVALUESPECIFICATIONITEM = 48;
  public int JJTSOURCESPECIFICATION = 49;
  public int JJTOWLRESTRICTION = 50;
  public int JJTOWLEXACTCARDINALITYRESTRICTION = 51;
  public int JJTOWLMAXCARDINALITYRESTRICTION = 52;
  public int JJTOWLMINCARDINALITYRESTRICTION = 53;
  public int JJTOWLHASVALUERESTRICTION = 54;
  public int JJTOWLALLVALUESFROMRESTRICTION = 55;
  public int JJTOWLDATAALLVALUESFROM = 56;
  public int JJTOWLOBJECTALLVALUESFROM = 57;
  public int JJTOWLSOMEVALUESFROMRESTRICTION = 58;
  public int JJTOWLOBJECTSOMEVALUESFROM = 59;
  public int JJTOWLDATASOMEVALUESFROM = 60;
  public int JJTOWLPROPERTYASSERTIONOBJECT = 61;
  public int JJTREFERENCE = 62;
  public int JJTREFERENCETYPE = 63;
  public int JJTVALUEENCODING = 64;
  public int JJTIRIENCODING = 65;
  public int JJTEMPTYLOCATIONSETTING = 66;
  public int JJTIFEXISTSDIRECTIVE = 67;
  public int JJTIFNOTEXISTSDIRECTIVE = 68;
  public int JJTEMPTYLITERALSETTING = 69;
  public int JJTEMPTYRDFSLABELSETTING = 70;
  public int JJTEMPTYRDFIDSETTING = 71;
  public int JJTSHIFTSETTING = 72;
  public int JJTDEFAULTLITERAL = 73;
  public int JJTDEFAULTLOCATIONVALUE = 74;
  public int JJTDEFAULTID = 75;
  public int JJTDEFAULTLABEL = 76;
  public int JJTPREFIX = 77;
  public int JJTLANGUAGE = 78;
  public int JJTNAMESPACE = 79;
  public int JJTVALUESPECIFICATION = 80;
  public int JJTVALUEEXTRACTIONFUNCTION = 81;
  public int JJTVALUEEXTRACTIONFUNCTIONARGUMENT = 82;


  public String[] jjtNodeName = {
    "Expression",
    "MMDirective",
    "MMExpression",
    "MMDefaultValueEncoding",
    "MMDefaultIRIEncoding",
    "MMDefaultShiftSetting",
    "MMDefaultEmptyLocationSetting",
    "MMDefaultEmptyLiteralSetting",
    "MMDefaultIfExistsSetting",
    "MMDefaultIfNotExistsSetting",
    "MMDefaultEmptyRDFIDSetting",
    "MMDefaultEmptyRDFSLabelSetting",
    "MMDefaultReferenceType",
    "MMDefaultLanguage",
    "MMDefaultPrefix",
    "MMDefaultNamespace",
    "MMDefaultPropertyValueType",
    "MMDefaultDatatypePropertyValueType",
    "MMDefaultAnnotationPropertyValueType",
    "MMDefaultPropertyType",
    "OWLClassDeclaration",
    "OWLObjectPropertyDeclaration",
    "OWLEquivalentClasses",
    "OWLSubclassOf",
    "OWLIndividualDeclaration",
    "OWLSameAs",
    "OWLDifferentFrom",
    "void",
    "Fact",
    "AnnotationFact",
    "OWLAnnotationProperty",
    "Name",
    "OWLAnnotationValue",
    "OWLLiteral",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "IRIRef",
    "OWLClassExpression",
    "OWLUnionClass",
    "OWLIntersectionClass",
    "OWLObjectOneOf",
    "OWLClass",
    "OWLObjectProperty",
    "OWLNamedIndividual",
    "OWLProperty",
    "Types",
    "ValueSpecificationItem",
    "SourceSpecification",
    "OWLRestriction",
    "OWLExactCardinalityRestriction",
    "OWLMaxCardinalityRestriction",
    "OWLMinCardinalityRestriction",
    "OWLHasValueRestriction",
    "OWLAllValuesFromRestriction",
    "OWLDataAllValuesFrom",
    "OWLObjectAllValuesFrom",
    "OWLSomeValuesFromRestriction",
    "OWLObjectSomeValuesFrom",
    "OWLDataSomeValuesFrom",
    "OWLPropertyAssertionObject",
    "Reference",
    "ReferenceType",
    "ValueEncoding",
    "IRIEncoding",
    "EmptyLocationSetting",
    "IfExistsDirective",
    "IfNotExistsDirective",
    "EmptyLiteralSetting",
    "EmptyRDFSLabelSetting",
    "EmptyRDFIDSetting",
    "ShiftSetting",
    "DefaultLiteral",
    "DefaultLocationValue",
    "DefaultID",
    "DefaultLabel",
    "Prefix",
    "Language",
    "Namespace",
    "ValueSpecification",
    "ValueExtractionFunction",
    "ValueExtractionFunctionArgument",
  };
}
/* JavaCC - OriginalChecksum=ee5dce357de8d109c723564dfa82c613 (do not edit this line) */
