/* Generated By:JavaCC: Do not edit this line. MappingMasterParserTreeConstants.java Version 6.1_2 */
package org.mm.parser;

public interface MappingMasterParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTMMDIRECTIVE = 1;
  public int JJTMMEXPRESSION = 2;
  public int JJTMMDEFAULTVALUEENCODING = 3;
  public int JJTMMDEFAULTSHIFTSETTING = 4;
  public int JJTMMDEFAULTEMPTYLOCATIONSETTING = 5;
  public int JJTMMDEFAULTEMPTYLITERALSETTING = 6;
  public int JJTMMDEFAULTIFEXISTSSETTING = 7;
  public int JJTMMDEFAULTIFNOTEXISTSSETTING = 8;
  public int JJTMMDEFAULTEMPTYRDFIDSETTING = 9;
  public int JJTMMDEFAULTEMPTYRDFSLABELSETTING = 10;
  public int JJTMMDEFAULTREFERENCETYPE = 11;
  public int JJTMMDEFAULTLANGUAGE = 12;
  public int JJTMMDEFAULTPREFIX = 13;
  public int JJTMMDEFAULTNAMESPACE = 14;
  public int JJTMMDEFAULTPROPERTYVALUETYPE = 15;
  public int JJTMMDEFAULTDATATYPEPROPERTYVALUETYPE = 16;
  public int JJTMMDEFAULTANNOTATIONPROPERTYVALUETYPE = 17;
  public int JJTMMDEFAULTPROPERTYTYPE = 18;
  public int JJTOWLCLASSDECLARATION = 19;
  public int JJTOWLEQUIVALENTCLASSES = 20;
  public int JJTOWLSUBCLASSOF = 21;
  public int JJTOWLINDIVIDUALDECLARATION = 22;
  public int JJTOWLSAMEAS = 23;
  public int JJTOWLDIFFERENTFROM = 24;
  public int JJTVOID = 25;
  public int JJTFACT = 26;
  public int JJTANNOTATIONFACT = 27;
  public int JJTOWLANNOTATIONPROPERTY = 28;
  public int JJTNAME = 29;
  public int JJTOWLANNOTATIONVALUE = 30;
  public int JJTOWLLITERAL = 31;
  public int JJTINTEGERLITERAL = 32;
  public int JJTFLOATLITERAL = 33;
  public int JJTSTRINGLITERAL = 34;
  public int JJTBOOLEANLITERAL = 35;
  public int JJTOWLCLASSEXPRESSION = 36;
  public int JJTOWLUNIONCLASS = 37;
  public int JJTOWLINTERSECTIONCLASS = 38;
  public int JJTOWLOBJECTONEOF = 39;
  public int JJTOWLCLASS = 40;
  public int JJTOWLNAMEDINDIVIDUAL = 41;
  public int JJTOWLPROPERTY = 42;
  public int JJTTYPES = 43;
  public int JJTVALUESPECIFICATIONITEM = 44;
  public int JJTSOURCESPECIFICATION = 45;
  public int JJTOWLRESTRICTION = 46;
  public int JJTOWLEXACTCARDINALITYRESTRICTION = 47;
  public int JJTOWLMAXCARDINALITYRESTRICTION = 48;
  public int JJTOWLMINCARDINALITYRESTRICTION = 49;
  public int JJTOWLHASVALUERESTRICTION = 50;
  public int JJTOWLALLVALUESFROMRESTRICTION = 51;
  public int JJTOWLDATAALLVALUESFROM = 52;
  public int JJTOWLOBJECTALLVALUESFROM = 53;
  public int JJTOWLSOMEVALUESFROMRESTRICTION = 54;
  public int JJTOWLOBJECTSOMEVALUESFROM = 55;
  public int JJTOWLDATASOMEVALUESFROM = 56;
  public int JJTOWLPROPERTYASSERTIONOBJECT = 57;
  public int JJTREFERENCE = 58;
  public int JJTREFERENCETYPE = 59;
  public int JJTVALUEENCODING = 60;
  public int JJTEMPTYLOCATIONSETTING = 61;
  public int JJTIFEXISTSDIRECTIVE = 62;
  public int JJTIFNOTEXISTSDIRECTIVE = 63;
  public int JJTEMPTYLITERALSETTING = 64;
  public int JJTEMPTYRDFSLABELSETTING = 65;
  public int JJTEMPTYRDFIDSETTING = 66;
  public int JJTSHIFTSETTING = 67;
  public int JJTDEFAULTLITERAL = 68;
  public int JJTDEFAULTLOCATIONVALUE = 69;
  public int JJTDEFAULTID = 70;
  public int JJTDEFAULTLABEL = 71;
  public int JJTPREFIX = 72;
  public int JJTLANGUAGE = 73;
  public int JJTNAMESPACE = 74;
  public int JJTVALUESPECIFICATION = 75;
  public int JJTVALUEEXTRACTIONFUNCTION = 76;
  public int JJTVALUEEXTRACTIONFUNCTIONARGUMENT = 77;


  public String[] jjtNodeName = {
    "Expression",
    "MMDirective",
    "MMExpression",
    "MMDefaultValueEncoding",
    "MMDefaultShiftSetting",
    "MMDefaultEmptyLocationSetting",
    "MMDefaultEmptyLiteralSetting",
    "MMDefaultIfExistsSetting",
    "MMDefaultIfNotExistsSetting",
    "MMDefaultEmptyRDFIDSetting",
    "MMDefaultEmptyRDFSLabelSetting",
    "MMDefaultReferenceType",
    "MMDefaultLanguage",
    "MMDefaultPrefix",
    "MMDefaultNamespace",
    "MMDefaultPropertyValueType",
    "MMDefaultDatatypePropertyValueType",
    "MMDefaultAnnotationPropertyValueType",
    "MMDefaultPropertyType",
    "OWLClassDeclaration",
    "OWLEquivalentClasses",
    "OWLSubclassOf",
    "OWLIndividualDeclaration",
    "OWLSameAs",
    "OWLDifferentFrom",
    "void",
    "Fact",
    "AnnotationFact",
    "OWLAnnotationProperty",
    "Name",
    "OWLAnnotationValue",
    "OWLLiteral",
    "IntegerLiteral",
    "FloatLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "OWLClassExpression",
    "OWLUnionClass",
    "OWLIntersectionClass",
    "OWLObjectOneOf",
    "OWLClass",
    "OWLNamedIndividual",
    "OWLProperty",
    "Types",
    "ValueSpecificationItem",
    "SourceSpecification",
    "OWLRestriction",
    "OWLExactCardinalityRestriction",
    "OWLMaxCardinalityRestriction",
    "OWLMinCardinalityRestriction",
    "OWLHasValueRestriction",
    "OWLAllValuesFromRestriction",
    "OWLDataAllValuesFrom",
    "OWLObjectAllValuesFrom",
    "OWLSomeValuesFromRestriction",
    "OWLObjectSomeValuesFrom",
    "OWLDataSomeValuesFrom",
    "OWLPropertyAssertionObject",
    "Reference",
    "ReferenceType",
    "ValueEncoding",
    "EmptyLocationSetting",
    "IfExistsDirective",
    "IfNotExistsDirective",
    "EmptyLiteralSetting",
    "EmptyRDFSLabelSetting",
    "EmptyRDFIDSetting",
    "ShiftSetting",
    "DefaultLiteral",
    "DefaultLocationValue",
    "DefaultID",
    "DefaultLabel",
    "Prefix",
    "Language",
    "Namespace",
    "ValueSpecification",
    "ValueExtractionFunction",
    "ValueExtractionFunctionArgument",
  };
}
/* JavaCC - OriginalChecksum=77a2214082790ca84346ba03d7820c20 (do not edit this line) */
